/* ===== Evolve data — exercise & food database (rarely changes) =====
   Security-hardening test build note: this file is reference data only.
   Loaded BEFORE app.js. Pure reference data + the tiny lookup maps. */
"use strict";

const GROUPS = ["Chest","Back","Shoulders","Arms","Legs","Core"];

const GICON={Chest:"🫁",Back:"🪽",Shoulders:"🏔️",Arms:"💪",Legs:"🦵",Core:"🎯"};

const GROUP_GLOW = {Chest:"#FF6A2C",Back:"#5AA9FF",Shoulders:"#FFC857",Arms:"#FF5470",Legs:"#2FE6A8",Core:"#A977FF"};

function ht(setup,move,cue,avoid){return {setup,move,cue,avoid};}

const MACHINES = [
/* CHEST */
{n:"Chest Press Machine",g:"Chest",h:ht("Set the seat so handles align with mid-chest. Sit back flat, feet planted.","Press handles forward until arms are nearly straight, then return under control.","Keep shoulder blades pulled back and down; drive through the chest, not the shoulders.","Don't lock elbows hard or let the weight slam back on the return.")},
{n:"Incline Chest Press Machine",g:"Chest",h:ht("Adjust seat low so handles sit at upper-chest height.","Press up and slightly forward, squeeze at the top, lower slowly.","Think 'up toward the collarbone' to bias the upper chest.","Avoid flaring elbows past 75°; keep wrists stacked over elbows.")},
{n:"Decline Chest Press Machine",g:"Chest",h:ht("Seat high so handles meet the lower chest line.","Press forward and slightly down, control the return.","Drive the handles together at lockout for a lower-pec squeeze.","Don't shrug the shoulders up during the press.")},
{n:"Pec Deck (Butterfly)",g:"Chest",h:ht("Set seat so forearm pads sit at chest height; elbows slightly bent.","Bring the pads together in a hugging arc until they nearly touch.","Squeeze the chest for a beat at the middle; lead with the elbows, not the hands.","Don't over-stretch behind the torso or use momentum to swing.")},
{n:"Cable Crossover (High to Low)",g:"Chest",h:ht("Set both pulleys high, grab handles, step forward into a split stance.","Sweep handles down and together toward your hips in an arc.","Slight forward lean; squeeze the lower chest at the bottom.","Don't let the cables yank your arms back fast on the return.")},
{n:"Cable Crossover (Low to High)",g:"Chest",h:ht("Set both pulleys low; staggered stance, slight forward lean.","Sweep handles up and together to upper-chest height.","Target the upper chest; finish with hands meeting in front of your face.","Avoid shrugging or using the front delts to lift.")},
{n:"Seated Cable Fly",g:"Chest",h:ht("Sit between two low/mid pulleys, soft bend in the elbows.","Bring handles together in front of the chest in a wide arc.","Keep the elbow angle fixed; move from the shoulder joint only.","Don't turn it into a press by bending and straightening the arms.")},
{n:"Smith Machine Bench Press",g:"Chest",h:ht("Lie on a flat bench centred under the bar; grip just wider than shoulders.","Unrack, lower bar to mid-chest, press straight up the fixed track.","Keep wrists stacked and elbows ~45° from the torso.","Don't bounce the bar off the chest; control every rep.")},
{n:"Smith Machine Incline Press",g:"Chest",h:ht("Incline bench at ~30°, bar over the upper chest.","Lower to the collarbone area, press straight up.","Tuck elbows slightly; keep the bar path over the upper chest.","Avoid setting the bench too steep, which shifts work to the shoulders.")},
{n:"Assisted Dip Machine (Chest)",g:"Chest",h:ht("Set assist weight, grip handles, lean the torso forward.","Lower until you feel a chest stretch, press back up.","Keep the forward lean and flared elbows to bias the chest.","Don't drop too deep if it strains the shoulders.")},
/* BACK */
{n:"Lat Pulldown",g:"Back",h:ht("Set the thigh pad snug; grab the bar wider than shoulders.","Pull the bar to the upper chest, driving elbows down and back.","Lead with the elbows; squeeze the lats and pause briefly.","Don't lean way back or yank with the lower back.")},
{n:"Close-Grip Lat Pulldown",g:"Back",h:ht("Use a V-handle or close grip; thighs pinned under the pad.","Pull the handle to the chest, elbows tracking close to the body.","Squeeze the mid-back; control the stretch at the top.","Avoid swinging or using momentum to finish reps.")},
{n:"Seated Cable Row",g:"Back",h:ht("Feet on the plate, slight knee bend, tall chest, V-handle in hands.","Pull the handle to the navel, driving elbows back past the ribs.","Squeeze the shoulder blades together; keep the torso still.","Don't round the back or rock for momentum.")},
{n:"Wide-Grip Seated Row Machine",g:"Back",h:ht("Chest against the pad, grab the wide handles.","Row the handles back, pulling elbows wide and high.","Targets upper back/rear delts; squeeze at the back.","Don't shrug excessively or jerk the weight.")},
{n:"T-Bar Row Machine",g:"Back",h:ht("Chest on the pad, feet planted, grip the handles.","Row the weight up toward you, driving elbows back.","Keep a braced core; squeeze the mid-back hard.","Avoid yanking with the lower back or standing up out of position.")},
{n:"Iso-Lateral Row Machine",g:"Back",h:ht("Chest against the pad, one handle per hand.","Row each handle back independently, elbow driving past the torso.","Full stretch forward, full squeeze back; even effort both sides.","Don't let the chest leave the pad to cheat the weight.")},
{n:"Assisted Pull-Up Machine",g:"Back",h:ht("Set assist weight, kneel/stand on the pad, wide overhand grip.","Pull your chest toward the bar, then lower with control.","Initiate from the lats; full hang at the bottom.","Don't kip or rush the descent.")},
{n:"Straight-Arm Cable Pulldown",g:"Back",h:ht("High pulley, straight bar, arms extended, slight hip hinge.","Pull the bar down to the thighs with straight arms.","Feel the lats stretch and contract; arms stay locked.","Don't bend the elbows or turn it into a triceps move.")},
{n:"Smith Machine Bent-Over Row",g:"Back",h:ht("Hinge at the hips ~45°, grip the bar just outside the knees.","Row the bar to the lower ribs along the fixed track.","Keep a flat back and braced core; drive elbows back.","Don't round the spine or stand upright as you pull.")},
{n:"Back Extension Machine (Hyperextension)",g:"Back",h:ht("Pad at the hip crease, ankles secured, arms crossed.","Lower the torso then rise until the body is straight.","Squeeze the glutes and lower back at the top.","Don't hyper-arch past straight at the top.")},
/* SHOULDERS */
{n:"Shoulder Press Machine",g:"Shoulders",h:ht("Seat set so handles start at shoulder height.","Press up until arms are nearly straight, lower under control.","Brace the core; press straight up, not forward.","Don't shrug at the top or bounce out of the bottom.")},
{n:"Smith Machine Shoulder Press",g:"Shoulders",h:ht("Seated upright, bar at upper-chest/chin height, grip just wider than shoulders.","Press the bar overhead, lower to chin level.","Keep the bar path vertical and core tight.","Avoid arching the lower back to push the weight.")},
{n:"Lateral Raise Machine",g:"Shoulders",h:ht("Pads against the outer arms, elbows slightly bent.","Raise the arms out to the sides to shoulder height.","Lead with the elbows; pause at the top.","Don't go above shoulder height or use a swing.")},
{n:"Cable Lateral Raise",g:"Shoulders",h:ht("Low pulley, handle in the far hand across the body.","Raise the arm out to the side to shoulder height.","Slight elbow bend; control the lowering phase.","Don't let the cable snap the arm back down.")},
{n:"Reverse Pec Deck (Rear Delt)",g:"Shoulders",h:ht("Face the pad, chest against it, grab the handles.","Open the arms back in a wide arc, squeezing the rear delts.","Keep a soft elbow; lead with the pinkies.","Don't use the upper traps or jerk the weight.")},
{n:"Cable Face Pull",g:"Shoulders",h:ht("Rope at upper-chest/face height, grip with thumbs back.","Pull the rope toward your face, hands splitting wide.","Externally rotate so knuckles face the ceiling at the end.","Don't let the elbows drop below the wrists.")},
{n:"Cable Front Raise",g:"Shoulders",h:ht("Low pulley behind you, straight bar or handle in front.","Raise the arms straight out to shoulder height.","Controlled tempo; brace the core to avoid swinging.","Don't lean back or use momentum from the hips.")},
{n:"Smith Machine Upright Row",g:"Shoulders",h:ht("Stand, grip the bar shoulder-width, arms hanging.","Pull the bar up the body to chest height, elbows leading high.","Keep the bar close; squeeze the delts/traps at the top.","Don't pull above the collarbone if shoulders feel pinched.")},
/* ARMS */
{n:"Cable Bicep Curl (Bar)",g:"Arms",h:ht("Low pulley, straight bar, elbows pinned to the sides.","Curl the bar up to the shoulders, squeeze, lower slowly.","Keep elbows fixed; only the forearms move.","Don't swing the body or let elbows drift forward.")},
{n:"Cable Rope Hammer Curl",g:"Arms",h:ht("Low pulley with a rope, neutral (thumbs-up) grip.","Curl the rope up keeping palms facing each other.","Targets the brachialis/forearm; pause at the top.","Don't flare elbows or rock for momentum.")},
{n:"Preacher Curl Machine",g:"Arms",h:ht("Upper arms flat on the pad, grip the handles.","Curl up, squeeze the biceps, lower to a near-straight arm.","Control the stretch at the bottom; keep arms on the pad.","Don't bounce out of the bottom or lift the elbows.")},
{n:"Seated Bicep Curl Machine",g:"Arms",h:ht("Chest/arms against the pad, grip the handles.","Curl the handles up, full squeeze, slow return.","Keep wrists neutral; controlled tempo both ways.","Don't let the weight pull the arms back fast.")},
{n:"Cable Concentration Curl",g:"Arms",h:ht("Low pulley, single handle, elbow braced on inner thigh or pad.","Curl the handle up toward the shoulder, peak squeeze.","Isolate the bicep; no body movement.","Don't use the shoulder to swing the weight up.")},
{n:"Tricep Pushdown (Bar)",g:"Arms",h:ht("High pulley, straight/angled bar, elbows pinned to sides.","Push the bar down until arms are straight, then return.","Keep elbows locked in place; squeeze the triceps at the bottom.","Don't lean over the bar or let elbows flare out.")},
{n:"Tricep Rope Pushdown",g:"Arms",h:ht("High pulley with a rope, elbows at the sides.","Push down and spread the rope apart at the bottom.","Full lockout and squeeze; control the way up.","Don't shrug or use the shoulders to push.")},
{n:"Overhead Cable Tricep Extension",g:"Arms",h:ht("Rope on a low/mid pulley, face away, rope behind the head.","Extend the arms overhead until straight, then bend back.","Keep elbows close and pointed forward; feel the stretch.","Don't let the elbows flare wide or arch the back.")},
{n:"Tricep Extension Machine",g:"Arms",h:ht("Seat set, forearms/hands on the pads or handles.","Press the handles down/out until arms straighten.","Squeeze the triceps at full extension.","Don't use bodyweight to slam the handles down.")},
{n:"Assisted Dip Machine (Triceps)",g:"Arms",h:ht("Set assist weight, grip handles, torso upright.","Lower until elbows reach ~90°, press back up.","Stay vertical and keep elbows tucked to hit triceps.","Don't lean forward (that shifts work to the chest).")},
{n:"Cable Tricep Kickback",g:"Arms",h:ht("Low pulley, hinge forward, upper arm parallel to the floor.","Extend the forearm back until the arm is straight.","Keep the upper arm still; squeeze at lockout.","Don't let the elbow drop or swing the arm.")},
/* LEGS */
{n:"Leg Press",g:"Legs",h:ht("Feet shoulder-width on the platform, back and hips flat on the pad.","Lower until knees reach ~90°, then press through the heels.","Keep knees tracking over the toes; don't lock out hard.","Don't let the lower back round off the pad at the bottom.")},
{n:"Hack Squat Machine",g:"Legs",h:ht("Shoulders under the pads, feet mid-platform, back flat.","Descend until thighs are parallel, drive up through the heels.","Knees track over toes; brace the core throughout.","Don't let the heels lift or the knees cave inward.")},
{n:"Smith Machine Squat",g:"Legs",h:ht("Bar across the upper back, feet slightly forward of the bar.","Squat down to parallel, then drive back up.","Keep the chest up and weight through mid-foot.","Don't round the back or let the knees collapse in.")},
{n:"Leg Extension",g:"Legs",h:ht("Pad on the lower shins, knees aligned with the pivot.","Extend the legs until straight, squeeze the quads, lower slowly.","Pause at the top; control the negative.","Don't kick explosively or let the weight crash down.")},
{n:"Lying Leg Curl",g:"Legs",h:ht("Lie face down, pad just above the heels, hips on the bench.","Curl the heels toward the glutes, squeeze, lower under control.","Keep the hips down; full range each rep.","Don't let the hips pop up to cheat the curl.")},
{n:"Seated Leg Curl",g:"Legs",h:ht("Thigh pad locked, ankle pad on the lower calves.","Curl the legs down and back, squeeze the hamstrings.","Keep the back against the seat; controlled tempo.","Don't use momentum or shorten the range.")},
{n:"Standing Calf Raise Machine",g:"Legs",h:ht("Shoulders under the pads, balls of the feet on the platform.","Rise onto the toes as high as possible, lower into a stretch.","Full range: deep stretch at the bottom, high squeeze at the top.","Don't bounce; pause briefly at the top and bottom.")},
{n:"Seated Calf Raise Machine",g:"Legs",h:ht("Knees under the pad, balls of feet on the platform.","Press up onto the toes, then lower into a deep stretch.","Targets the soleus; slow controlled reps.","Don't use a tiny range of motion.")},
{n:"Leg Press Calf Raise",g:"Legs",h:ht("Feet low on the leg-press platform, legs nearly straight.","Push the platform away with the toes, then stretch back.","Big squeeze at the top, full stretch at the bottom.","Keep a slight knee bend; don't lock the knees hard.")},
{n:"Hip Abduction Machine",g:"Legs",h:ht("Sit back, knees against the outer pads.","Push the knees outward against resistance, then return slowly.","Squeeze the glutes at the widest point.","Don't slam the pads back together on the return.")},
{n:"Hip Adduction Machine",g:"Legs",h:ht("Sit back, knees on the inside of the pads, legs apart.","Squeeze the legs together against resistance, return slowly.","Controlled both directions; feel the inner thighs.","Don't let the weight yank the legs apart fast.")},
{n:"Glute Kickback Machine",g:"Legs",h:ht("Chest on the pad, foot on the platform/lever.","Press the leg back and up until the glute fully contracts.","Squeeze the glute hard at the top; control the return.","Don't arch the lower back to gain range.")},
{n:"Cable Glute Kickback",g:"Legs",h:ht("Ankle strap on a low pulley, slight forward lean, hold support.","Drive the leg back and up, squeezing the glute.","Keep the movement at the hip; brace the core.","Don't swing the leg or twist the hips.")},
{n:"Hip Thrust Machine",g:"Legs",h:ht("Back/shoulders on the pad, hips under the lever, feet planted.","Drive the hips up until the body is straight, squeeze glutes.","Tuck the chin, full lockout, lower under control.","Don't over-arch the lower back at the top.")},
{n:"Smith Machine Lunge",g:"Legs",h:ht("Bar on the upper back, one foot forward in a split stance.","Lower the back knee toward the floor, then drive up.","Keep the torso tall; front knee tracks over the foot.","Don't let the front knee cave or the back rounding.")},
/* CORE */
{n:"Cable Crunch",g:"Core",h:ht("Kneel under a high rope, rope by the head, hips hinged.","Crunch down by rounding the spine, elbows toward thighs.","Pull with the abs, not the arms; squeeze hard.","Don't pull with the lower back or just bow at the hips.")},
{n:"Ab Crunch Machine",g:"Core",h:ht("Chest/handles set, feet under the pads.","Crunch the torso forward by contracting the abs.","Move from the spine flexing, not the hip flexors.","Don't yank with the arms or use momentum.")},
{n:"Rotary Torso Machine",g:"Core",h:ht("Seat the legs locked, torso against the pads.","Rotate the torso to one side against resistance, control back.","Twist from the obliques; keep the hips fixed.","Don't use a heavy load that yanks the spine.")},
{n:"Hanging Leg Raise (Captain's Chair)",g:"Core",h:ht("Forearms on the pads, back against the rest, legs hanging.","Raise the knees (or straight legs) toward the chest.","Curl the pelvis up; pause at the top.","Don't swing the legs or use momentum.")},
{n:"Cable Woodchopper",g:"Core",h:ht("High pulley, handle in both hands, stand side-on.","Pull diagonally across the body down to the opposite hip.","Rotate through the core; pivot the back foot.","Don't pull with the arms alone or round the back.")},
/* --- expanded: converging / plate-loaded / extra machines --- */
{n:"Converging Chest Press",g:"Chest",h:ht("Seat so handles align with mid-chest; back flat against the pad.","Press the handles forward and inward as they converge toward each other.","The converging path squeezes the inner chest at lockout — pause there.","Don't let the shoulders roll forward or lock the elbows hard.")},
{n:"Converging Incline Press",g:"Chest",h:ht("Set the seat low so handles sit at the upper chest; back flat.","Press up and inward along the converging arc, squeeze, lower slowly.","Drive toward the collarbone to bias the upper chest.","Avoid shrugging the traps to move the weight.")},
{n:"Plate-Loaded Chest Press",g:"Chest",h:ht("Load plates evenly; seat so handles meet the mid-chest.","Press the handles forward to full extension, control the return.","Keep shoulder blades retracted and chest proud throughout.","Don't bounce out of the bottom or let one side lead.")},
{n:"Iso-Lateral Chest Press",g:"Chest",h:ht("One handle per hand, seat at mid-chest height.","Press each arm independently to full extension.","Even effort both sides; full stretch and full squeeze.","Don't let the stronger arm dominate the rep.")},
{n:"Seated Dip Machine",g:"Chest",h:ht("Sit upright (or lean forward for chest), grip the handles.","Press the handles down until the arms straighten, control back up.","Lean forward and flare elbows slightly to hit the chest.","Don't drop too deep if the shoulders feel strained.")},
{n:"Converging Shoulder Press",g:"Shoulders",h:ht("Seat so handles start at shoulder height; brace the core.","Press up and inward along the converging path to lockout.","Handles meet overhead for a strong delt squeeze — pause briefly.","Don't arch the lower back or press forward of the head.")},
{n:"Plate-Loaded Shoulder Press",g:"Shoulders",h:ht("Load plates evenly; handles at shoulder height, sit tall.","Press straight overhead to near lockout, lower under control.","Keep wrists stacked over elbows; ribs down.","Avoid bouncing out of the bottom or flaring excessively.")},
{n:"Iso-Lateral Shoulder Press",g:"Shoulders",h:ht("One handle per hand at shoulder height.","Press each arm overhead independently, control the descent.","Match both sides; full range each rep.","Don't shrug the traps to finish the press.")},
{n:"Machine Rear Delt Row",g:"Shoulders",h:ht("Chest on the pad, grip the high handles.","Row the handles back and out, leading with the elbows.","Squeeze the rear delts and upper back; keep a soft elbow.","Don't yank or use the lower back.")},
{n:"Cable Y-Raise",g:"Shoulders",h:ht("Two low pulleys, handles crossed, arms down.","Raise the arms up and out into a Y overhead.","Thumbs up; controlled tempo for the rear/side delts.","Don't shrug or use momentum.")},
{n:"Converging Lat Pulldown",g:"Back",h:ht("Thighs under the pad, grip the wide handles.","Pull down and in as the handles converge toward the chest.","Drive elbows down and back; squeeze the lats at the bottom.","Don't lean back excessively or use momentum.")},
{n:"Iso-Lateral Lat Pulldown",g:"Back",h:ht("Thighs pinned, one handle per hand overhead.","Pull each handle down independently to the shoulder.","Full stretch at the top, full squeeze at the bottom.","Don't let the torso swing to assist.")},
{n:"Plate-Loaded Row",g:"Back",h:ht("Chest on the pad, load plates evenly, grip the handles.","Row the handles back, driving the elbows past the ribs.","Squeeze the shoulder blades; keep the chest on the pad.","Don't heave with the lower back.")},
{n:"Low Row Machine",g:"Back",h:ht("Chest against the pad, grip the low handles.","Row up and back toward the lower ribs, squeeze the mid-back.","Keep the torso still; lead with the elbows.","Don't shrug or round the spine.")},
{n:"High Row Machine",g:"Back",h:ht("Chest on the pad, grip the high handles overhead.","Pull the handles down and back toward the chest.","Targets the upper lats; squeeze at the bottom.","Don't lean back to cheat the weight.")},
{n:"Pullover Machine",g:"Back",h:ht("Elbows on the pads, hands on the bar, seat set.","Pull the bar down in an arc using the lats, control back up.","Feel the lat stretch at the top and contraction at the bottom.","Don't use the arms to push; drive with the lats.")},
{n:"Diverging Seated Row",g:"Back",h:ht("Chest on the pad, grip the handles which spread as you row.","Row back and out, opening the handles, squeeze the back.","Drive elbows back and slightly out; full contraction.","Don't jerk or let the chest leave the pad.")},
{n:"Assisted Chin-Up Machine",g:"Back",h:ht("Set assist weight, kneel/stand on the pad, underhand grip.","Pull your chest toward the bar, lower to a full hang.","Initiate from the lats and biceps; controlled descent.","Don't bounce out of the bottom.")},
{n:"Machine Preacher Curl",g:"Arms",h:ht("Upper arms on the pad, grip the handles.","Curl up to a full contraction, lower to a near-straight arm.","Keep the arms planted; control the negative.","Don't lift the elbows or swing.")},
{n:"Machine Tricep Dip",g:"Arms",h:ht("Sit upright, grip the handles, elbows tucked.","Press the handles down until arms straighten, control back.","Stay vertical to keep tension on the triceps.","Don't lean forward (shifts work to the chest).")},
{n:"Cable Reverse Curl",g:"Arms",h:ht("Low pulley, straight bar, overhand (palms-down) grip.","Curl the bar up keeping the palms facing down.","Targets the forearms/brachialis; elbows pinned.","Don't swing or let the wrists drop.")},
{n:"Cable Wrist Curl",g:"Arms",h:ht("Low pulley, forearms resting on the thighs or a bench.","Curl the wrists up, then lower for a full forearm stretch.","Slow controlled reps; isolate the forearms.","Don't use the whole arm to lift.")},
{n:"Pendulum Squat",g:"Legs",h:ht("Shoulders under the pads, feet on the platform, back flat.","Descend along the arc to depth, drive up through mid-foot.","Knees track over toes; brace the core throughout.","Don't let the heels lift or knees cave.")},
{n:"Belt Squat Machine",g:"Legs",h:ht("Belt around the hips, stand on the platform, grip supports.","Squat down to depth, drive up through the heels.","Keeps load off the spine — stay tall and braced.","Don't round the back or cut depth short.")},
{n:"Reverse Hack Squat",g:"Legs",h:ht("Face the pad, shoulders under the supports, feet on platform.","Squat down facing the machine, drive back up.","Great for quads and glutes; keep the chest up.","Don't let the knees collapse inward.")},
{n:"V-Squat Machine",g:"Legs",h:ht("Shoulders under the pads, feet forward on the platform.","Lower to parallel along the V-path, press up through the heels.","Keep the core tight and weight through mid-foot.","Don't bounce at the bottom.")},
{n:"Glute Drive Machine",g:"Legs",h:ht("Back on the pad, hips under the lever, feet planted.","Drive the hips up to full extension, squeeze the glutes.","Tuck the chin, pause at the top, lower under control.","Don't over-arch the lower back.")},
{n:"Standing Leg Curl Machine",g:"Legs",h:ht("Stand, one ankle behind the pad, hips against the support.","Curl the heel toward the glute, squeeze, lower slowly.","Keep the hips still; isolate the hamstring.","Don't swing the leg or arch the back.")},
{n:"Horizontal Leg Press",g:"Legs",h:ht("Sit back, feet on the platform shoulder-width.","Press the platform away to near lockout, return to ~90°.","Heels down, knees tracking over the toes.","Don't lock the knees hard or round the lower back.")},
{n:"Smith Machine Calf Raise",g:"Legs",h:ht("Bar on the upper back, balls of feet on a block/platform.","Rise onto the toes as high as possible, lower into a stretch.","Full range with a pause top and bottom.","Don't bounce through the reps.")},
{n:"Ab Coaster",g:"Core",h:ht("Kneel on the pads, grip the handles above.","Curl the knees up and toward the chest along the track.","Pull with the lower abs; control the way down.","Don't use momentum to swing the carriage.")},
{n:"Oblique Crunch Machine",g:"Core",h:ht("Seat set, side against the pad, grip the handle.","Crunch sideways, contracting the obliques, return slowly.","Move from the waist; keep the hips planted.","Don't use a heavy load that yanks the spine.")},
{n:"Hanging Knee Raise Station",g:"Core",h:ht("Hang from the bar or use the arm pads, legs down.","Raise the knees toward the chest, curling the pelvis up.","Pause at the top; lower with control.","Don't swing or use momentum.")}
];

const MACHINE_BY_NAME = {}; MACHINES.forEach(m=>MACHINE_BY_NAME[m.n]=m);

const SUBGROUPS={
  Chest:["Upper chest","Mid chest","Lower chest"],
  Back:["Lats","Traps / upper back","Lower back"],
  Shoulders:["Front delts","Side delts","Rear delts"],
  Arms:["Biceps","Triceps","Forearms"],
  Legs:["Quads","Hamstrings","Glutes","Calves"],
  Core:["Abs","Obliques","Lower back"]
};

const FREEWEIGHTS = [
/* CHEST */
{n:"Barbell Bench Press",g:"Chest",fw:1,h:ht("Lie flat, eyes under the bar, grip just wider than shoulders, feet planted.","Unrack, lower the bar to the mid-chest, press up to lockout.","Tuck elbows ~45°, squeeze the shoulder blades, keep wrists stacked.","Don't bounce the bar off the chest or flare the elbows wide.")},
{n:"Incline Barbell Press",g:"Chest",fw:1,h:ht("Bench at ~30°, grip just wider than shoulders, bar over the upper chest.","Lower to the collarbone area, press straight up.","Drive toward the upper chest; keep the core braced.","Avoid setting the bench too steep or arching hard.")},
{n:"Decline Barbell Press",g:"Chest",fw:1,h:ht("Decline bench, feet secured, bar over the lower chest.","Lower to the lower chest, press up to lockout.","Targets the lower pecs; controlled tempo.","Don't lose control unracking without a spotter.")},
{n:"Dumbbell Bench Press",g:"Chest",fw:1,h:ht("Lie flat, dumbbells at the sides of the chest.","Press up until the dumbbells nearly touch, lower with a stretch.","Wrists stacked over elbows; full range of motion.","Don't clash the dumbbells or drop them at the bottom.")},
{n:"Incline Dumbbell Press",g:"Chest",fw:1,h:ht("Bench ~30°, dumbbells at upper-chest height.","Press up and slightly together, lower under control.","Squeeze the upper chest at the top.","Avoid flaring the elbows past 75°.")},
{n:"Dumbbell Fly",g:"Chest",fw:1,h:ht("Lie flat, dumbbells above the chest, slight elbow bend.","Open the arms wide in an arc, then bring them back together.","Keep the elbow angle fixed; feel the chest stretch.","Don't turn it into a press or go too heavy.")},
{n:"Dumbbell Pullover",g:"Chest",fw:1,h:ht("Lie across or along a bench, one dumbbell held above the chest.","Lower the dumbbell back behind the head, then pull it back over.","Feel the stretch across the chest and lats.","Don't over-extend the lower back.")},
{n:"Weighted Push-up",g:"Chest",fw:1,h:ht("Plate on the upper back (or weighted vest), hands shoulder-width.","Lower the chest to the floor, press up.","Body in a straight line; brace the core.","Don't let the hips sag.")},
/* BACK */
{n:"Deadlift",g:"Back",fw:1,h:ht("Bar over mid-foot, hinge and grip outside the knees, flat back, chest up.","Drive through the floor, stand tall locking hips and knees together.","Keep the bar close to the body; brace the core hard.","Don't round the lower back or jerk the bar off the floor.")},
{n:"Barbell Row",g:"Back",fw:1,h:ht("Hinge ~45°, flat back, grip the bar just outside the knees.","Row the bar to the lower ribs, driving the elbows back.","Squeeze the shoulder blades; keep the torso steady.","Don't stand up as you pull or round the spine.")},
{n:"Pendlay Row",g:"Back",fw:1,h:ht("Bar on the floor, torso parallel, grip outside the knees.","Explosively row the bar to the chest, return to the floor each rep.","Strict torso position; reset on the floor between reps.","Don't use the legs or hips to heave the weight.")},
{n:"Dumbbell Row",g:"Back",fw:1,h:ht("One knee and hand on a bench, dumbbell hanging in the other hand.","Row the dumbbell to the hip, squeeze the back, lower slowly.","Keep the back flat; drive the elbow past the torso.","Don't twist the torso to lift heavier.")},
{n:"Pull-up (weighted)",g:"Back",fw:1,h:ht("Belt with plate (or vest), overhand grip wider than shoulders.","Pull the chest toward the bar, lower to a full hang.","Lead with the lats; control the descent.","Don't kip or shorten the range.")},
{n:"Chin-up (weighted)",g:"Back",fw:1,h:ht("Underhand grip, optional added weight.","Pull up until the chin clears the bar, lower with control.","Squeeze the lats and biceps at the top.","Don't swing for momentum.")},
{n:"Barbell Shrug",g:"Back",fw:1,h:ht("Stand holding the bar at arm's length in front.","Shrug the shoulders straight up toward the ears, lower slowly.","Pause at the top; keep the arms straight.","Don't roll the shoulders or use momentum.")},
{n:"Dumbbell Shrug",g:"Back",fw:1,h:ht("Dumbbells at the sides, arms straight.","Shrug the shoulders up, squeeze the traps, lower slowly.","Straight arms; controlled tempo.","Don't roll the shoulders forward or back.")},
{n:"Rack Pull",g:"Back",fw:1,h:ht("Bar set on rack pins around knee height, grip outside the knees.","Drive the hips forward to lock out, lower back to the pins.","Flat back, brace hard; emphasises the upper back/lockout.","Don't round the spine under heavy load.")},
/* SHOULDERS */
{n:"Overhead Barbell Press",g:"Shoulders",fw:1,h:ht("Bar at the front-rack on the upper chest, grip just outside shoulders.","Press the bar overhead to lockout, lower to the chest.","Brace the core and glutes; bar travels in a straight line.","Don't over-arch the lower back to press.")},
{n:"Seated Dumbbell Press",g:"Shoulders",fw:1,h:ht("Seated upright, dumbbells at shoulder height.","Press overhead until nearly locked out, lower under control.","Keep wrists stacked; ribs down.","Avoid clashing the dumbbells or arching.")},
{n:"Arnold Press",g:"Shoulders",fw:1,h:ht("Seated, dumbbells in front at shoulder height, palms facing you.","Rotate the palms out as you press overhead, reverse on the way down.","Smooth rotation; controlled tempo.","Don't rush the rotation or use momentum.")},
{n:"Dumbbell Lateral Raise",g:"Shoulders",fw:1,h:ht("Stand, dumbbells at the sides, slight elbow bend.","Raise the arms out to shoulder height, lower slowly.","Lead with the elbows; pause at the top.","Don't swing or shrug the traps up.")},
{n:"Dumbbell Front Raise",g:"Shoulders",fw:1,h:ht("Dumbbells in front of the thighs.","Raise one or both arms to shoulder height in front, lower slowly.","Controlled tempo; brace the core.","Don't lean back or use momentum.")},
{n:"Bent-Over Dumbbell Raise",g:"Shoulders",fw:1,h:ht("Hinge forward, dumbbells hanging, slight elbow bend.","Raise the arms out to the sides, squeezing the rear delts.","Lead with the pinkies; keep the back flat.","Don't use the traps or jerk the weight.")},
{n:"Barbell Upright Row",g:"Shoulders",fw:1,h:ht("Stand, grip the bar shoulder-width, arms hanging.","Pull the bar up the body to chest height, elbows leading high.","Keep the bar close; squeeze the delts.","Stop if the shoulders pinch; don't pull too high.")},
/* ARMS */
{n:"Barbell Curl",g:"Arms",fw:1,h:ht("Stand, shoulder-width underhand grip, elbows at the sides.","Curl the bar to the shoulders, squeeze, lower slowly.","Keep the elbows pinned; no swinging.","Don't rock the torso to lift.")},
{n:"EZ-Bar Curl",g:"Arms",fw:1,h:ht("Grip the angled bar, elbows tucked.","Curl up, squeeze the biceps, lower under control.","Easier on the wrists than a straight bar.","Don't let the elbows drift forward.")},
{n:"Dumbbell Curl",g:"Arms",fw:1,h:ht("Dumbbells at the sides, palms forward (or rotate up).","Curl to the shoulders, squeeze, lower slowly.","Alternate or together; keep elbows fixed.","Don't swing the dumbbells up.")},
{n:"Hammer Curl",g:"Arms",fw:1,h:ht("Dumbbells held neutral (palms facing each other).","Curl up keeping the neutral grip, lower slowly.","Targets the brachialis and forearms.","Don't flare the elbows or rock.")},
{n:"Concentration Curl",g:"Arms",fw:1,h:ht("Seated, elbow braced on the inner thigh, dumbbell hanging.","Curl up to a peak contraction, lower slowly.","Isolate the bicep; no body movement.","Don't use the shoulder to swing.")},
{n:"Preacher Curl (EZ-bar)",g:"Arms",fw:1,h:ht("Upper arms on the preacher pad, grip the EZ-bar.","Curl up, squeeze, lower to a near-straight arm.","Control the stretch; arms stay planted.","Don't bounce out of the bottom.")},
{n:"Close-Grip Bench Press",g:"Arms",fw:1,h:ht("Lie flat, grip the bar shoulder-width or slightly narrower.","Lower to the lower chest with tucked elbows, press up.","Drive with the triceps; keep elbows close.","Don't grip too narrow (wrist strain).")},
{n:"Skull Crushers",g:"Arms",fw:1,h:ht("Lie flat, EZ-bar/dumbbells held over the chest.","Bend the elbows to lower toward the forehead, extend back up.","Keep the upper arms still; elbows point forward.","Don't flare the elbows or let them drift back.")},
{n:"Dumbbell Overhead Tricep Extension",g:"Arms",fw:1,h:ht("Hold one dumbbell overhead with both hands.","Lower it behind the head by bending the elbows, extend back up.","Keep the elbows close and pointed up.","Don't let the elbows flare wide.")},
{n:"Dumbbell Kickback",g:"Arms",fw:1,h:ht("Hinge forward, upper arm parallel to the floor.","Extend the forearm back until straight, squeeze.","Keep the upper arm still; controlled reps.","Don't swing the arm or drop the elbow.")},
{n:"Dips (weighted)",g:"Arms",fw:1,h:ht("Parallel bars, belt with plate (or vest), torso upright.","Lower until elbows reach ~90°, press back up.","Stay vertical and tuck elbows for the triceps.","Don't drop too deep if the shoulders strain.")},
/* LEGS */
{n:"Back Squat",g:"Legs",fw:1,h:ht("Bar on the upper back, feet shoulder-width, toes slightly out.","Sit down and back to depth, drive up through mid-foot.","Chest up, knees track over toes, brace the core.","Don't let the knees cave or the back round.")},
{n:"Front Squat",g:"Legs",fw:1,h:ht("Bar in the front rack across the shoulders, elbows high.","Squat down keeping the torso upright, drive up.","Elbows up throughout; weight through mid-foot.","Don't let the elbows drop or the chest fall.")},
{n:"Romanian Deadlift",g:"Legs",fw:1,h:ht("Stand with the bar, soft knees, flat back.","Hinge the hips back, lower the bar along the legs, drive hips forward.","Feel the hamstring stretch; keep the bar close.","Don't round the back or squat the weight down.")},
{n:"Stiff-Leg Deadlift",g:"Legs",fw:1,h:ht("Bar in hands, legs nearly straight, flat back.","Hinge to lower the bar toward the floor, return to standing.","Strong hamstring stretch; controlled tempo.","Don't round the spine; keep a slight knee bend.")},
{n:"Barbell Lunge",g:"Legs",fw:1,h:ht("Bar on the upper back, step one foot forward.","Lower the back knee toward the floor, drive up. Alternate.","Torso tall; front knee tracks over the foot.","Don't let the front knee cave inward.")},
{n:"Walking Lunge",g:"Legs",fw:1,h:ht("Dumbbells at the sides or bar on the back.","Step forward into a lunge, then bring the back foot through to the next step.","Controlled steps; chest up.","Don't let the knee crash into the floor.")},
{n:"Dumbbell Lunge",g:"Legs",fw:1,h:ht("Dumbbells at the sides, step forward into a lunge.","Lower the back knee, drive up. Alternate legs.","Keep the torso upright and core braced.","Don't lean forward excessively.")},
{n:"Goblet Squat",g:"Legs",fw:1,h:ht("Hold a dumbbell/kettlebell at the chest.","Squat to depth keeping the chest up, drive up.","Elbows inside the knees at the bottom.","Don't round the upper back.")},
{n:"Bulgarian Split Squat",g:"Legs",fw:1,h:ht("Rear foot on a bench, dumbbells at the sides.","Lower the front leg to parallel, drive up.","Most of the weight on the front leg; torso tall.","Don't let the front knee collapse in.")},
{n:"Barbell Hip Thrust",g:"Legs",fw:1,h:ht("Upper back on a bench, bar across the hips, feet planted.","Drive the hips up to full extension, squeeze the glutes.","Tuck the chin, ribs down, pause at the top.","Don't over-arch the lower back.")},
{n:"Dumbbell Step-up",g:"Legs",fw:1,h:ht("Dumbbells at the sides, step onto a box/bench.","Drive up to stand on the box, control back down. Alternate.","Drive through the heel of the lead foot.","Don't push off the back foot too much.")},
{n:"Standing Calf Raise (barbell/db)",g:"Legs",fw:1,h:ht("Weight on the back or dumbbells in hand, balls of feet on a block.","Rise onto the toes, lower into a deep stretch.","Full range, pause at top and bottom.","Don't bounce through reps.")},
/* CORE */
{n:"Weighted Sit-up",g:"Core",fw:1,h:ht("Lie back, knees bent, hold a plate on the chest.","Sit up by contracting the abs, lower with control.","Lead with the chest; avoid yanking the neck.","Don't use momentum to fling up.")},
{n:"Russian Twist (weighted)",g:"Core",fw:1,h:ht("Sit leaning back, feet up, hold a plate/dumbbell.","Rotate the torso side to side, tapping near the hips.","Twist from the core; controlled tempo.","Don't just move the arms.")},
{n:"Hanging Leg Raise",g:"Core",fw:1,h:ht("Hang from a bar, legs straight.","Raise the legs toward the chest, curling the pelvis up.","Control the lower; pause at the top.","Don't swing or use momentum.")},
{n:"Ab Wheel Rollout",g:"Core",fw:1,h:ht("Kneel holding the ab wheel under the shoulders.","Roll forward extending the body, then pull back in.","Brace the core hard; keep a neutral spine.","Don't let the lower back sag.")},
{n:"Dumbbell Side Bend",g:"Core",fw:1,h:ht("Stand, dumbbell in one hand at the side.","Bend sideways toward the weight, then back up. Switch sides.","Move only at the waist; controlled tempo.","Don't twist or use momentum.")},
{n:"Plank (weighted)",g:"Core",fw:1,h:ht("Forearm plank with a plate on the upper back.","Hold a straight line from head to heels.","Brace the core and squeeze the glutes.","Don't let the hips sag or pike up.")}
];

const FW_BY_NAME = {}; FREEWEIGHTS.forEach(m=>FW_BY_NAME[m.n]=m);

const EX_BY_NAME = Object.assign({}, MACHINE_BY_NAME, FW_BY_NAME);

const PRESET_DAYS = {
  "Push":["Chest Press Machine","Incline Chest Press Machine","Shoulder Press Machine","Lateral Raise Machine","Tricep Rope Pushdown","Overhead Cable Tricep Extension"],
  "Pull":["Lat Pulldown","Seated Cable Row","Iso-Lateral Row Machine","Reverse Pec Deck (Rear Delt)","Cable Bicep Curl (Bar)","Preacher Curl Machine"],
  "Legs":["Leg Press","Hack Squat Machine","Leg Extension","Lying Leg Curl","Hip Thrust Machine","Standing Calf Raise Machine"],
  "Upper":["Chest Press Machine","Lat Pulldown","Shoulder Press Machine","Seated Cable Row","Cable Bicep Curl (Bar)","Tricep Rope Pushdown"],
  "Full Body":["Leg Press","Chest Press Machine","Lat Pulldown","Shoulder Press Machine","Seated Leg Curl","Cable Crunch"]
};

const HOME = [
 {n:"Push-ups",eq:["none"],t:"Chest",d:"Hands shoulder-width, body in a straight line. Lower the chest to the floor, press back up. Knees down to scale.",reps:"3 × 12"},
 {n:"Incline Push-ups",eq:["bench"],t:"Chest",d:"Hands on a bench/step. Lower the chest to the edge, press up. Easier than floor push-ups.",reps:"3 × 12"},
 {n:"Pike Push-ups",eq:["none"],t:"Shoulders",d:"Hips high in an inverted V. Lower the crown of the head toward the floor, press up. Hits the shoulders.",reps:"3 × 10"},
 {n:"Bodyweight Squats",eq:["none"],t:"Legs",d:"Feet shoulder-width. Sit back and down to parallel, drive up through the heels.",reps:"3 × 15"},
 {n:"Reverse Lunges",eq:["none"],t:"Legs",d:"Step one foot back, lower the back knee toward the floor, drive up. Alternate legs.",reps:"3 × 10/leg"},
 {n:"Glute Bridge",eq:["none"],t:"Glutes",d:"Lie on your back, knees bent. Drive the hips up, squeeze the glutes, lower slowly.",reps:"3 × 15"},
 {n:"Wall Sit",eq:["none"],t:"Legs",d:"Back against a wall, thighs parallel to the floor. Hold the position.",reps:"3 × 40s"},
 {n:"Calf Raises",eq:["none"],t:"Calves",d:"Rise onto the toes as high as possible, lower into a stretch. Hold a wall for balance.",reps:"3 × 20"},
 {n:"Plank",eq:["none"],t:"Core",d:"Forearms down, body in a straight line, core braced. Hold without sagging the hips.",reps:"3 × 45s"},
 {n:"Mountain Climbers",eq:["none"],t:"Core",d:"In a push-up position, drive the knees toward the chest alternately at pace.",reps:"3 × 30s"},
 {n:"Bicycle Crunches",eq:["none"],t:"Core",d:"On your back, bring opposite elbow to knee, alternating in a pedalling motion.",reps:"3 × 20"},
 {n:"Crunches",eq:["none"],t:"Core",d:"On your back, knees bent. Curl the shoulders off the floor by contracting the abs.",reps:"3 × 20"},
 {n:"Superman",eq:["none"],t:"Back",d:"Lie face down, lift the arms and legs off the floor, squeeze the lower back, lower slowly.",reps:"3 × 15"},
 {n:"Burpees",eq:["none"],t:"Full Body",d:"Squat, kick back to a plank, do a push-up, jump the feet in and jump up.",reps:"3 × 10"},
 {n:"Chair/Bench Dips",eq:["bench"],t:"Triceps",d:"Hands on a bench behind you, lower the body by bending the elbows, press back up.",reps:"3 × 12"},
 {n:"Step-ups",eq:["bench"],t:"Legs",d:"Step one foot onto a bench, drive up to stand, control back down. Alternate.",reps:"3 × 10/leg"},
 {n:"Bulgarian Split Squat",eq:["bench"],t:"Legs",d:"Rear foot on a bench, lower the front leg to parallel, drive up.",reps:"3 × 10/leg"},
 {n:"DB Goblet Squat",eq:["dumbbell"],t:"Legs",d:"Hold a dumbbell at the chest. Squat to parallel, drive up through the heels.",reps:"3 × 12"},
 {n:"DB Shoulder Press",eq:["dumbbell"],t:"Shoulders",d:"Dumbbells at shoulder height, press overhead, lower with control.",reps:"3 × 10"},
 {n:"DB Floor Press",eq:["dumbbell"],t:"Chest",d:"Lie on the floor, press dumbbells up from the chest until arms are straight.",reps:"3 × 12"},
 {n:"DB Row",eq:["dumbbell"],t:"Back",d:"Hinge forward, row the dumbbell to the hip, squeeze the back, lower slowly.",reps:"3 × 10/side"},
 {n:"DB Bicep Curl",eq:["dumbbell"],t:"Arms",d:"Curl the dumbbells to the shoulders, elbows pinned, lower under control.",reps:"3 × 12"},
 {n:"DB Romanian Deadlift",eq:["dumbbell"],t:"Hamstrings",d:"Hinge at the hips, lower the dumbbells along the legs, drive the hips forward to stand.",reps:"3 × 12"},
 {n:"DB Lateral Raise",eq:["dumbbell"],t:"Shoulders",d:"Raise the dumbbells out to the sides to shoulder height, lower slowly.",reps:"3 × 15"},
 {n:"DB Lunge",eq:["dumbbell"],t:"Legs",d:"Dumbbells at the sides, step into a lunge, drive up. Alternate legs.",reps:"3 × 10/leg"},
 {n:"Band Pull-apart",eq:["band"],t:"Back",d:"Hold a band at chest height, pull it apart by squeezing the shoulder blades.",reps:"3 × 15"},
 {n:"Band Row",eq:["band"],t:"Back",d:"Anchor the band, pull the handles to the ribs, squeeze the back.",reps:"3 × 15"},
 {n:"Band Squat",eq:["band"],t:"Legs",d:"Stand on the band, handles at the shoulders, squat against the resistance.",reps:"3 × 15"},
 {n:"Band Chest Press",eq:["band"],t:"Chest",d:"Anchor the band behind you, press the handles forward to full extension.",reps:"3 × 15"},
 {n:"Band Lateral Raise",eq:["band"],t:"Shoulders",d:"Stand on the band, raise the arms out to the sides to shoulder height.",reps:"3 × 15"},
 {n:"Band Bicep Curl",eq:["band"],t:"Arms",d:"Stand on the band, curl the handles to the shoulders, lower slowly.",reps:"3 × 15"},
 {n:"Pull-ups",eq:["pullup"],t:"Back",d:"Overhand grip, pull the chest toward the bar, lower to a full hang.",reps:"3 × max"},
 {n:"Chin-ups",eq:["pullup"],t:"Back",d:"Underhand grip, pull up until the chin clears the bar, lower with control.",reps:"3 × max"},
 {n:"Hanging Knee Raise",eq:["pullup"],t:"Core",d:"Hang from the bar, raise the knees toward the chest, lower slowly.",reps:"3 × 12"},
 {n:"Kettlebell Swing",eq:["kettlebell"],t:"Full Body",d:"Hinge at the hips, hike the bell back, snap the hips forward to swing it to chest height.",reps:"3 × 15"},
 {n:"KB Goblet Squat",eq:["kettlebell"],t:"Legs",d:"Hold the bell at the chest, squat to parallel, drive up.",reps:"3 × 12"},
 {n:"KB Clean & Press",eq:["kettlebell"],t:"Full Body",d:"Clean the bell to the shoulder, press overhead, return under control. Switch sides.",reps:"3 × 8/side"},
 {n:"Diamond Push-ups",eq:["none"],t:"Triceps",d:"Hands together forming a diamond under the chest. Lower and press up — hits the triceps hard.",reps:"3 × 10"},
 {n:"Wide Push-ups",eq:["none"],t:"Chest",d:"Hands wider than shoulders. Lower the chest and press up — emphasises the chest.",reps:"3 × 12"},
 {n:"Decline Push-ups",eq:["bench"],t:"Chest",d:"Feet raised on a bench, hands on the floor. Lower and press — targets the upper chest.",reps:"3 × 12"},
 {n:"Pseudo Planche Push-ups",eq:["none"],t:"Shoulders",d:"Hands by the waist, lean forward over them, lower and press. Heavy shoulder emphasis.",reps:"3 × 8"},
 {n:"Towel Row (door)",eq:["none"],t:"Back",d:"Loop a towel around a sturdy handle, lean back with straight arms and row your chest toward it.",reps:"3 × 12"},
 {n:"Inverted Row (under table)",eq:["none"],t:"Back",d:"Lie under a sturdy table, grip the edge and pull your chest up to it, body straight.",reps:"3 × 10"},
 {n:"Pike Push-up (feet raised)",eq:["bench"],t:"Shoulders",d:"Feet on a bench, hips high. Lower the head toward the floor and press — strong shoulder builder.",reps:"3 × 8"},
 {n:"Chair Tricep Extension",eq:["none"],t:"Triceps",d:"Hands on a low surface behind you, bend at the elbows to lower, then extend. Keep elbows tucked.",reps:"3 × 12"},
 {n:"DB Hammer Curl",eq:["dumbbell"],t:"Arms",d:"Curl the dumbbells with palms facing each other. Targets the biceps and forearms.",reps:"3 × 12"},
 {n:"DB Tricep Kickback",eq:["dumbbell"],t:"Triceps",d:"Hinge forward, upper arm parallel to the floor, extend the forearm back and squeeze.",reps:"3 × 12"},
 {n:"DB Pullover",eq:["dumbbell"],t:"Back",d:"Lie back, hold one dumbbell over the chest, lower it behind the head and pull back over.",reps:"3 × 12"},
 {n:"Band Overhead Press",eq:["band"],t:"Shoulders",d:"Stand on the band, press the handles overhead to full extension, lower slowly.",reps:"3 × 12"},
 {n:"Band Tricep Pushdown",eq:["band"],t:"Triceps",d:"Anchor the band high, push the handle down until the arm is straight, control back up.",reps:"3 × 15"},
 {n:"Donkey Kicks",eq:["none"],t:"Glutes",d:"On all fours, drive one heel toward the ceiling, squeezing the glute. Alternate.",reps:"3 × 15/leg"},
 {n:"Single-leg Glute Bridge",eq:["none"],t:"Glutes",d:"Bridge on one leg, drive the hips up and squeeze the glute. Switch legs.",reps:"3 × 12/leg"},
 {n:"Jump Squats",eq:["none"],t:"Legs",d:"Squat down then explode up into a jump, land soft and repeat.",reps:"3 × 12"},
 {n:"Curtsy Lunge",eq:["none"],t:"Legs",d:"Step one leg diagonally behind the other into a lunge, drive up. Alternate.",reps:"3 × 10/leg"},
 {n:"Leg Raises",eq:["none"],t:"Core",d:"Lie flat, raise straight legs to vertical, lower slowly without touching the floor.",reps:"3 × 15"},
 {n:"Russian Twists",eq:["none"],t:"Core",d:"Sit leaning back, feet up, rotate the torso side to side tapping the floor each side.",reps:"3 × 20"},
 {n:"Flutter Kicks",eq:["none"],t:"Core",d:"Lie flat, lift the heels off the floor and alternate small up-down kicks.",reps:"3 × 30s"},
 {n:"Side Plank",eq:["none"],t:"Core",d:"On one forearm, body in a straight line on its side, hold. Switch sides.",reps:"3 × 30s/side"}
];

const HOME_EQUIP = [
 {id:"none",label:"Bodyweight only"},{id:"dumbbell",label:"Dumbbells"},
 {id:"band",label:"Resistance bands"},{id:"pullup",label:"Pull-up bar"},
 {id:"kettlebell",label:"Kettlebell"},{id:"bench",label:"Bench / chair"}
];

const CARDIO = [
 /* machines */
 {n:"Treadmill — walk",t:"machine",met:3.8,ic:"🚶"},
 {n:"Treadmill — brisk walk",t:"machine",met:5.0,ic:"🚶"},
 {n:"Treadmill — incline walk",t:"machine",met:6.5,ic:"⛰️"},
 {n:"Treadmill — jog",t:"machine",met:7.0,ic:"🏃"},
 {n:"Treadmill — run",t:"machine",met:9.8,ic:"🏃"},
 {n:"Treadmill — sprints",t:"machine",met:12.0,ic:"💨"},
 {n:"Stationary bike — light",t:"machine",met:5.5,ic:"🚴"},
 {n:"Stationary bike — moderate",t:"machine",met:7.0,ic:"🚴"},
 {n:"Stationary bike — vigorous",t:"machine",met:10.5,ic:"🚴"},
 {n:"Recumbent bike",t:"machine",met:5.0,ic:"🚲"},
 {n:"Spin bike",t:"machine",met:8.5,ic:"🚴"},
 {n:"Elliptical / cross-trainer",t:"machine",met:5.5,ic:"🌀"},
 {n:"Rowing machine — moderate",t:"machine",met:7.0,ic:"🚣"},
 {n:"Rowing machine — vigorous",t:"machine",met:8.5,ic:"🚣"},
 {n:"Stair climber / stepmill",t:"machine",met:9.0,ic:"🪜"},
 {n:"Assault / air bike",t:"machine",met:8.0,ic:"🌬️"},
 {n:"Ski erg",t:"machine",met:7.0,ic:"🎿"},
 {n:"Arc trainer",t:"machine",met:6.5,ic:"🌀"},
 {n:"Jacob's ladder",t:"machine",met:9.0,ic:"🪜"},
 {n:"Curved manual treadmill",t:"machine",met:8.5,ic:"🏃"},
 /* at home / no machine */
 {n:"Walking",t:"home",met:3.5,ic:"🚶"},
 {n:"Brisk walking",t:"home",met:4.3,ic:"🚶"},
 {n:"Running (outdoors)",t:"home",met:9.8,ic:"🏃"},
 {n:"Hiking",t:"home",met:6.0,ic:"🥾"},
 {n:"Cycling (outdoors)",t:"home",met:7.5,ic:"🚲"},
 {n:"Jump rope",t:"home",met:12.0,ic:"🪢"},
 {n:"Jumping jacks",t:"home",met:8.0,ic:"🤸"},
 {n:"High knees",t:"home",met:8.0,ic:"🦵"},
 {n:"Burpees",t:"home",met:8.0,ic:"🔥"},
 {n:"Mountain climbers",t:"home",met:8.0,ic:"⛰️"},
 {n:"Shadow boxing",t:"home",met:6.0,ic:"🥊"},
 {n:"Skipping (light)",t:"home",met:8.8,ic:"🪢"},
 {n:"Stair climbing (home)",t:"home",met:8.0,ic:"🪜"},
 {n:"Dancing",t:"home",met:5.0,ic:"💃"},
 {n:"Swimming",t:"home",met:8.0,ic:"🏊"},
 {n:"HIIT circuit",t:"home",met:8.5,ic:"⚡"},
 {n:"Star jumps",t:"home",met:8.0,ic:"⭐"},
 {n:"Boxing (bag work)",t:"home",met:7.8,ic:"🥊"},
 {n:"Rowing (home machine)",t:"home",met:7.0,ic:"🚣"},
 {n:"Elliptical (home)",t:"home",met:5.5,ic:"🌀"}
];

const FOODS = [
 ["Chicken breast (grilled)",165,31,0,3.6,"Poultry & egg"],
 ["Chicken breast (raw)",120,23,0,2.6,"Poultry & egg"],
 ["Chicken thigh (cooked)",209,26,0,11,"Poultry & egg"],
 ["Chicken thigh (skinless)",177,24,0,8.2,"Poultry & egg"],
 ["Chicken drumstick (cooked)",172,28,0,5.7,"Poultry & egg"],
 ["Chicken wing (cooked)",203,30,0,8.1,"Poultry & egg"],
 ["Roast chicken (mixed)",190,29,0,7.5,"Poultry & egg"],
 ["Chicken mince (cooked)",189,27,0,8.5,"Poultry & egg"],
 ["Rotisserie chicken",184,28,0,7.4,"Poultry & egg"],
 ["Fried chicken (breaded)",246,28,9,12,"Poultry & egg"],
 ["Chicken nuggets",296,15,18,18,"Poultry & egg"],
 ["Chicken sausage",172,17,3,10,"Poultry & egg"],
 ["Turkey breast (cooked)",135,30,0,1,"Poultry & egg"],
 ["Turkey mince (cooked)",203,27,0,10,"Poultry & egg"],
 ["Turkey bacon",226,29,3,11,"Poultry & egg"],
 ["Turkey slice (deli)",104,17,3,2,"Poultry & egg"],
 ["Duck breast (cooked)",201,24,0,11,"Poultry & egg"],
 ["Duck (roasted, with skin)",337,19,0,28,"Poultry & egg"],
 ["Goose (roasted)",305,25,0,22,"Poultry & egg"],
 ["Quail (cooked)",227,25,0,14,"Poultry & egg"],
 ["Egg (whole)",143,13,1.1,9.5,"Poultry & egg"],
 ["Egg white",52,11,0.7,0.2,"Poultry & egg"],
 ["Egg yolk",322,16,3.6,27,"Poultry & egg"],
 ["Boiled egg",155,13,1.1,11,"Poultry & egg"],
 ["Fried egg",196,14,0.8,15,"Poultry & egg"],
 ["Scrambled egg",149,10,1.6,11,"Poultry & egg"],
 ["Omelette (plain)",154,11,0.6,12,"Poultry & egg"],
 ["Duck egg",185,13,1.5,14,"Poultry & egg"],
 ["Quail egg",158,13,0.4,11,"Poultry & egg"],
 ["Beef steak (sirloin)",212,29,0,10,"Red meat & pork"],
 ["Beef steak (ribeye)",291,24,0,21,"Red meat & pork"],
 ["Beef steak (fillet)",207,28,0,10,"Red meat & pork"],
 ["Lean beef mince 5% (cooked)",170,26,0,7,"Red meat & pork"],
 ["Beef mince 20% (cooked)",254,26,0,17,"Red meat & pork"],
 ["Roast beef",215,28,0,11,"Red meat & pork"],
 ["Beef brisket (cooked)",243,29,0,13,"Red meat & pork"],
 ["Beef short rib",295,22,0,23,"Red meat & pork"],
 ["Corned beef",250,27,1,15,"Red meat & pork"],
 ["Beef jerky",410,33,11,26,"Red meat & pork"],
 ["Ground beef patty",250,26,0,16,"Red meat & pork"],
 ["Veal (cooked)",196,31,0,7,"Red meat & pork"],
 ["Lamb chop (cooked)",294,25,0,21,"Red meat & pork"],
 ["Lamb leg (roasted)",240,26,0,15,"Red meat & pork"],
 ["Lamb mince (cooked)",282,25,0,20,"Red meat & pork"],
 ["Lamb shoulder",284,24,0,21,"Red meat & pork"],
 ["Pork chop (cooked)",231,26,0,14,"Red meat & pork"],
 ["Pork loin (cooked)",242,27,0,14,"Red meat & pork"],
 ["Pork belly",518,9,0,53,"Red meat & pork"],
 ["Pork shoulder (pulled)",211,24,0,13,"Red meat & pork"],
 ["Pork mince (cooked)",263,26,0,18,"Red meat & pork"],
 ["Bacon (cooked)",541,37,1.4,42,"Red meat & pork"],
 ["Bacon (back, grilled)",287,24,0,21,"Red meat & pork"],
 ["Ham (sliced)",145,21,1.5,6,"Red meat & pork"],
 ["Gammon (cooked)",204,25,0,11,"Red meat & pork"],
 ["Sausage (pork, cooked)",301,18,2,25,"Red meat & pork"],
 ["Chorizo",455,24,2,38,"Red meat & pork"],
 ["Salami",336,22,2,27,"Red meat & pork"],
 ["Pepperoni",504,20,1.2,46,"Red meat & pork"],
 ["Prosciutto",250,26,1,16,"Red meat & pork"],
 ["Pancetta",315,18,0,27,"Red meat & pork"],
 ["Black pudding",379,13,15,30,"Red meat & pork"],
 ["Hot dog / frankfurter",290,11,4,26,"Red meat & pork"],
 ["Meatball (beef)",197,12,5,14,"Red meat & pork"],
 ["Venison (cooked)",158,30,0,3.2,"Red meat & pork"],
 ["Bison (cooked)",143,28,0,2.4,"Red meat & pork"],
 ["Liver (beef, cooked)",191,29,5,5,"Red meat & pork"],
 ["Kidney (cooked)",158,27,0,5,"Red meat & pork"],
 ["Salmon (cooked)",208,20,0,13,"Fish & seafood"],
 ["Salmon (smoked)",117,18,0,4.3,"Fish & seafood"],
 ["Salmon (raw)",182,20,0,11,"Fish & seafood"],
 ["Tuna (canned in water)",116,26,0,1,"Fish & seafood"],
 ["Tuna (canned in oil)",198,29,0,8,"Fish & seafood"],
 ["Tuna steak (cooked)",184,30,0,6,"Fish & seafood"],
 ["Cod (cooked)",105,23,0,1,"Fish & seafood"],
 ["Cod (battered)",230,12,18,13,"Fish & seafood"],
 ["Haddock (cooked)",112,24,0,1,"Fish & seafood"],
 ["Pollock (cooked)",111,23,0,1.2,"Fish & seafood"],
 ["Tilapia (cooked)",129,26,0,2.7,"Fish & seafood"],
 ["Sea bass (cooked)",124,23,0,2.6,"Fish & seafood"],
 ["Mackerel (cooked)",262,24,0,18,"Fish & seafood"],
 ["Sardines (canned)",208,25,0,11,"Fish & seafood"],
 ["Herring (cooked)",203,23,0,12,"Fish & seafood"],
 ["Trout (cooked)",190,27,0,8.5,"Fish & seafood"],
 ["Halibut (cooked)",140,27,0,3,"Fish & seafood"],
 ["Snapper (cooked)",128,26,0,1.7,"Fish & seafood"],
 ["Anchovies (canned)",210,29,0,10,"Fish & seafood"],
 ["Plaice (cooked)",91,19,0,1.5,"Fish & seafood"],
 ["Prawns (cooked)",99,24,0.2,0.3,"Fish & seafood"],
 ["King prawns",85,20,0,0.5,"Fish & seafood"],
 ["Shrimp (breaded)",242,12,22,12,"Fish & seafood"],
 ["Crab (cooked)",97,19,0,1.5,"Fish & seafood"],
 ["Lobster (cooked)",89,19,0,0.9,"Fish & seafood"],
 ["Mussels (cooked)",172,24,7,4.5,"Fish & seafood"],
 ["Oysters",81,9,4,2.3,"Fish & seafood"],
 ["Scallops (cooked)",137,24,6,1,"Fish & seafood"],
 ["Squid (calamari, fried)",175,15,8,7,"Fish & seafood"],
 ["Octopus (cooked)",164,30,4,2,"Fish & seafood"],
 ["Clams (cooked)",148,26,5,2,"Fish & seafood"],
 ["Fish fingers",230,12,20,12,"Fish & seafood"],
 ["Fishcake",180,9,16,9,"Fish & seafood"],
 ["Caviar",264,25,4,18,"Fish & seafood"],
 ["Crab stick (surimi)",95,8,14,0.5,"Fish & seafood"],
 ["Tofu (firm)",144,15,3,8,"Legumes & plant protein"],
 ["Tofu (silken)",55,5,2,3,"Legumes & plant protein"],
 ["Tempeh",192,20,8,11,"Legumes & plant protein"],
 ["Seitan",141,25,4,2,"Legumes & plant protein"],
 ["Edamame",121,12,9,5,"Legumes & plant protein"],
 ["Soybeans (cooked)",173,17,10,9,"Legumes & plant protein"],
 ["Black beans (cooked)",132,8.9,24,0.5,"Legumes & plant protein"],
 ["Kidney beans (cooked)",127,8.7,23,0.5,"Legumes & plant protein"],
 ["Chickpeas (cooked)",164,8.9,27,2.6,"Legumes & plant protein"],
 ["Lentils (cooked)",116,9,20,0.4,"Legumes & plant protein"],
 ["Red lentils (cooked)",116,9,20,0.4,"Legumes & plant protein"],
 ["Pinto beans (cooked)",143,9,26,0.7,"Legumes & plant protein"],
 ["Cannellini beans",114,8,21,0.6,"Legumes & plant protein"],
 ["Butter beans",115,7,20,0.5,"Legumes & plant protein"],
 ["Black-eyed peas",116,8,21,0.5,"Legumes & plant protein"],
 ["Split peas (cooked)",118,8,21,0.4,"Legumes & plant protein"],
 ["Baked beans",94,4.8,16,0.5,"Legumes & plant protein"],
 ["Hummus",166,8,14,10,"Legumes & plant protein"],
 ["Falafel",333,13,32,18,"Legumes & plant protein"],
 ["Refried beans",91,5,15,1.5,"Legumes & plant protein"],
 ["Mung beans (cooked)",105,7,19,0.4,"Legumes & plant protein"],
 ["Soya mince (TVP, cooked)",105,17,7,0.5,"Legumes & plant protein"],
 ["Veggie burger",170,16,12,7,"Legumes & plant protein"],
 ["Quorn pieces",94,15,4.5,2,"Legumes & plant protein"],
 ["Peanut (as protein)",567,26,16,49,"Legumes & plant protein"],
 ["Whole milk",61,3.2,4.8,3.3,"Dairy & alternatives"],
 ["Semi-skimmed milk",47,3.5,4.8,1.7,"Dairy & alternatives"],
 ["Skimmed milk",34,3.4,5,0.1,"Dairy & alternatives"],
 ["Lactose-free milk",42,3.4,5,1.5,"Dairy & alternatives"],
 ["Buttermilk",62,3.3,4.8,3.3,"Dairy & alternatives"],
 ["Greek yogurt (0%)",59,10,3.6,0.4,"Dairy & alternatives"],
 ["Greek yogurt (2%)",73,10,4,1.9,"Dairy & alternatives"],
 ["Greek yogurt (full fat)",97,9,4,5,"Dairy & alternatives"],
 ["Natural yogurt",61,3.5,4.7,3.3,"Dairy & alternatives"],
 ["Low-fat yogurt",63,5,7,1.5,"Dairy & alternatives"],
 ["Fruit yogurt (low fat)",95,4,17,1.5,"Dairy & alternatives"],
 ["Skyr",63,11,4,0.2,"Dairy & alternatives"],
 ["Kefir",41,3.3,4.5,1,"Dairy & alternatives"],
 ["Cottage cheese",98,11,3.4,4.3,"Dairy & alternatives"],
 ["Cottage cheese (low fat)",72,12,3,1,"Dairy & alternatives"],
 ["Quark",68,12,4,0.2,"Dairy & alternatives"],
 ["Cream cheese",342,6,4,34,"Dairy & alternatives"],
 ["Light cream cheese",201,8,8,16,"Dairy & alternatives"],
 ["Sour cream",198,2,4,19,"Dairy & alternatives"],
 ["Double cream",449,1.7,2.7,48,"Dairy & alternatives"],
 ["Single cream",193,3,4,19,"Dairy & alternatives"],
 ["Whipped cream",257,3,12,22,"Dairy & alternatives"],
 ["Crème fraîche",299,2.4,3,30,"Dairy & alternatives"],
 ["Custard",122,3,17,4.5,"Dairy & alternatives"],
 ["Ice cream (vanilla)",207,3.5,24,11,"Dairy & alternatives"],
 ["Ice cream (chocolate)",216,3.8,28,11,"Dairy & alternatives"],
 ["Frozen yogurt",127,3,22,3,"Dairy & alternatives"],
 ["Gelato",160,4,28,4,"Dairy & alternatives"],
 ["Rice pudding",97,3,16,2.5,"Dairy & alternatives"],
 ["Almond milk (unsweetened)",13,0.4,0.6,1.1,"Dairy & alternatives"],
 ["Almond milk (sweetened)",24,0.4,3,1.2,"Dairy & alternatives"],
 ["Oat milk",47,1,7,1.5,"Dairy & alternatives"],
 ["Soy milk",43,3.3,5,1.8,"Dairy & alternatives"],
 ["Coconut milk drink",30,0.2,2,2.5,"Dairy & alternatives"],
 ["Coconut milk (canned)",230,2.3,6,24,"Dairy & alternatives"],
 ["Rice milk",47,0.3,9.5,1,"Dairy & alternatives"],
 ["Cashew milk",25,0.5,2,2,"Dairy & alternatives"],
 ["Cheddar",402,25,1.3,33,"Cheese"],
 ["Mature cheddar",410,25,0.1,34,"Cheese"],
 ["Mozzarella",280,28,3.1,17,"Cheese"],
 ["Fresh mozzarella",254,18,3,19,"Cheese"],
 ["Parmesan",431,38,4,29,"Cheese"],
 ["Feta",264,14,4,21,"Cheese"],
 ["Brie",334,21,0.5,28,"Cheese"],
 ["Camembert",300,20,0.5,24,"Cheese"],
 ["Goat cheese",364,22,2.5,30,"Cheese"],
 ["Blue cheese",353,21,2.3,29,"Cheese"],
 ["Gouda",356,25,2.2,27,"Cheese"],
 ["Edam",357,25,1.4,28,"Cheese"],
 ["Emmental",380,28,1,30,"Cheese"],
 ["Gruyère",413,30,0.4,32,"Cheese"],
 ["Halloumi",321,22,2,26,"Cheese"],
 ["Ricotta",174,11,3,13,"Cheese"],
 ["Mascarpone",429,4,4,44,"Cheese"],
 ["Cream cheese spread",250,6,5,24,"Cheese"],
 ["Cottage (as cheese)",98,11,3.4,4.3,"Cheese"],
 ["Paneer",265,18,1.2,21,"Cheese"],
 ["Swiss cheese",380,27,5,28,"Cheese"],
 ["Provolone",351,26,2.1,27,"Cheese"],
 ["Manchego",398,26,0.5,32,"Cheese"],
 ["Babybel",290,23,0,22,"Cheese"],
 ["Cheese spread (processed)",290,16,8,22,"Cheese"],
 ["Cheese slice (processed)",280,16,7,21,"Cheese"],
 ["Grana padano",398,33,0,29,"Cheese"],
 ["Mascarpone light",260,5,5,25,"Cheese"],
 ["Wensleydale",375,23,0.1,31,"Cheese"],
 ["White rice (cooked)",130,2.7,28,0.3,"Grains, rice & pasta"],
 ["Brown rice (cooked)",112,2.6,24,0.9,"Grains, rice & pasta"],
 ["Basmati rice (cooked)",121,3,25,0.4,"Grains, rice & pasta"],
 ["Jasmine rice (cooked)",129,2.9,28,0.3,"Grains, rice & pasta"],
 ["Wild rice (cooked)",101,4,21,0.3,"Grains, rice & pasta"],
 ["Egg fried rice",163,4,26,5,"Grains, rice & pasta"],
 ["Pilau rice",185,3,30,6,"Grains, rice & pasta"],
 ["Risotto",166,4,22,6,"Grains, rice & pasta"],
 ["Pasta (cooked)",157,5.8,31,0.9,"Grains, rice & pasta"],
 ["Wholewheat pasta (cooked)",124,5,26,1.1,"Grains, rice & pasta"],
 ["Spaghetti (cooked)",158,6,31,0.9,"Grains, rice & pasta"],
 ["Penne (cooked)",157,5.8,31,0.9,"Grains, rice & pasta"],
 ["Macaroni (cooked)",157,5.8,31,0.9,"Grains, rice & pasta"],
 ["Lasagne sheets (cooked)",157,5.8,31,0.9,"Grains, rice & pasta"],
 ["Gnocchi",133,3,28,0.5,"Grains, rice & pasta"],
 ["Egg noodles (cooked)",138,4.5,25,2.1,"Grains, rice & pasta"],
 ["Rice noodles (cooked)",108,1.8,24,0.2,"Grains, rice & pasta"],
 ["Udon noodles (cooked)",125,3,27,0.4,"Grains, rice & pasta"],
 ["Soba noodles (cooked)",99,5,21,0.1,"Grains, rice & pasta"],
 ["Ramen noodles (cooked)",136,4,27,1,"Grains, rice & pasta"],
 ["Instant noodles (prepared)",185,4,25,7,"Grains, rice & pasta"],
 ["Couscous (cooked)",112,3.8,23,0.2,"Grains, rice & pasta"],
 ["Quinoa (cooked)",120,4.4,21,1.9,"Grains, rice & pasta"],
 ["Bulgur wheat (cooked)",83,3,19,0.2,"Grains, rice & pasta"],
 ["Pearl barley (cooked)",123,2.3,28,0.4,"Grains, rice & pasta"],
 ["Polenta (cooked)",70,1.6,15,0.3,"Grains, rice & pasta"],
 ["Buckwheat (cooked)",92,3.4,20,0.6,"Grains, rice & pasta"],
 ["Farro (cooked)",130,5,26,1,"Grains, rice & pasta"],
 ["Millet (cooked)",119,3.5,24,1,"Grains, rice & pasta"],
 ["Freekeh (cooked)",110,4,22,0.6,"Grains, rice & pasta"],
 ["Oats (dry)",389,17,66,7,"Grains, rice & pasta"],
 ["Porridge (with water)",68,2.4,12,1.4,"Grains, rice & pasta"],
 ["Porridge (with milk)",116,4.5,16,4,"Grains, rice & pasta"],
 ["Overnight oats",140,5,22,4,"Grains, rice & pasta"],
 ["White bread",265,9,49,3.2,"Bread & bakery"],
 ["Wholemeal bread",247,13,41,4.2,"Bread & bakery"],
 ["Brown bread",250,10,46,3,"Bread & bakery"],
 ["Sourdough",289,12,56,1.5,"Bread & bakery"],
 ["Rye bread",259,9,48,3.3,"Bread & bakery"],
 ["Multigrain bread",265,13,43,4.2,"Bread & bakery"],
 ["Ciabatta",271,9,52,3,"Bread & bakery"],
 ["Baguette",274,9,55,2,"Bread & bakery"],
 ["Pitta bread",275,9,55,1.2,"Bread & bakery"],
 ["Naan bread",310,9,49,9,"Bread & bakery"],
 ["Chapati",297,11,46,7,"Bread & bakery"],
 ["Tortilla wrap",312,8,49,8,"Bread & bakery"],
 ["Wholemeal wrap",290,10,42,8,"Bread & bakery"],
 ["Bagel (plain)",257,10,51,1.5,"Bread & bakery"],
 ["Bagel (cinnamon raisin)",274,10,55,1.7,"Bread & bakery"],
 ["English muffin",227,9,44,1.8,"Bread & bakery"],
 ["Crumpet",177,5,36,0.6,"Bread & bakery"],
 ["Croissant",406,8,46,21,"Bread & bakery"],
 ["Pain au chocolat",414,8,45,23,"Bread & bakery"],
 ["Brioche",330,9,51,11,"Bread & bakery"],
 ["Focaccia",273,7,42,9,"Bread & bakery"],
 ["Crackers (cream)",502,9,62,24,"Bread & bakery"],
 ["Cream crackers",440,10,68,13,"Bread & bakery"],
 ["Rice cakes",387,8,82,3,"Bread & bakery"],
 ["Oatcakes",430,10,60,18,"Bread & bakery"],
 ["Crispbread",333,9,68,1.5,"Bread & bakery"],
 ["Breadsticks",408,12,71,8,"Bread & bakery"],
 ["Garlic bread",350,8,40,17,"Bread & bakery"],
 ["Pretzels",380,10,80,3,"Bread & bakery"],
 ["Soft pretzel",338,8,69,3,"Bread & bakery"],
 ["Hot cross bun",260,7,49,5,"Bread & bakery"],
 ["Scone (plain)",364,8,54,14,"Bread & bakery"],
 ["Bread roll (white)",265,9,49,3.2,"Bread & bakery"],
 ["Pancakes",227,6,28,9,"Bread & bakery"],
 ["Waffle",291,7,33,14,"Bread & bakery"],
 ["French toast",229,8,25,11,"Bread & bakery"],
 ["Doughnut (plain)",452,5,51,25,"Bread & bakery"],
 ["Doughnut (jam)",340,5,49,14,"Bread & bakery"],
 ["Muffin (blueberry)",377,5,54,16,"Bread & bakery"],
 ["Muffin (chocolate)",400,6,52,19,"Bread & bakery"],
 ["Banana bread",326,5,54,11,"Bread & bakery"],
 ["Cornbread",330,7,49,12,"Bread & bakery"],
 ["Flatbread",290,9,49,6,"Bread & bakery"],
 ["Cornflakes",357,7.5,84,0.4,"Cereal & breakfast"],
 ["Bran flakes",355,10,67,2,"Cereal & breakfast"],
 ["Rice cereal (crisped)",382,6,87,1,"Cereal & breakfast"],
 ["Frosted flakes",375,5,90,0.5,"Cereal & breakfast"],
 ["Muesli",362,10,66,6,"Cereal & breakfast"],
 ["Granola",471,10,64,20,"Cereal & breakfast"],
 ["Low-fat granola",380,9,72,6,"Cereal & breakfast"],
 ["Weetabix",362,12,69,2,"Cereal & breakfast"],
 ["Shredded wheat",340,11,68,2.5,"Cereal & breakfast"],
 ["Porridge oats (instant)",380,11,60,8,"Cereal & breakfast"],
 ["Cheerios (oat)",379,11,73,7,"Cereal & breakfast"],
 ["Special flakes",379,15,77,1.5,"Cereal & breakfast"],
 ["Chocolate cereal",385,7,77,5,"Cereal & breakfast"],
 ["Honey cereal loops",379,7,85,4,"Cereal & breakfast"],
 ["Grits (cooked)",59,1.4,13,0.2,"Cereal & breakfast"],
 ["Breakfast biscuit",450,7,68,16,"Cereal & breakfast"],
 ["Pop tart",407,4,71,12,"Cereal & breakfast"],
 ["Crunchy nut cereal",398,7,82,4,"Cereal & breakfast"],
 ["Coco pops",383,5,87,2.5,"Cereal & breakfast"],
 ["Banana",89,1.1,23,0.3,"Fruit"],
 ["Apple",52,0.3,14,0.2,"Fruit"],
 ["Orange",47,0.9,12,0.1,"Fruit"],
 ["Strawberries",32,0.7,7.7,0.3,"Fruit"],
 ["Blueberries",57,0.7,14,0.3,"Fruit"],
 ["Raspberries",52,1.2,12,0.7,"Fruit"],
 ["Blackberries",43,1.4,10,0.5,"Fruit"],
 ["Grapes",69,0.7,18,0.2,"Fruit"],
 ["Pineapple",50,0.5,13,0.1,"Fruit"],
 ["Mango",60,0.8,15,0.4,"Fruit"],
 ["Avocado",160,2,9,15,"Fruit"],
 ["Watermelon",30,0.6,8,0.2,"Fruit"],
 ["Cantaloupe melon",34,0.8,8,0.2,"Fruit"],
 ["Honeydew melon",36,0.5,9,0.1,"Fruit"],
 ["Pear",57,0.4,15,0.1,"Fruit"],
 ["Kiwi",61,1.1,15,0.5,"Fruit"],
 ["Peach",39,0.9,10,0.3,"Fruit"],
 ["Nectarine",44,1.1,11,0.3,"Fruit"],
 ["Plum",46,0.7,11,0.3,"Fruit"],
 ["Apricot",48,1.4,11,0.4,"Fruit"],
 ["Cherries",63,1.1,16,0.2,"Fruit"],
 ["Pomegranate",83,1.7,19,1.2,"Fruit"],
 ["Fig (fresh)",74,0.8,19,0.3,"Fruit"],
 ["Dates (medjool)",277,1.8,75,0.2,"Fruit"],
 ["Grapefruit",42,0.8,11,0.1,"Fruit"],
 ["Lemon",29,1.1,9,0.3,"Fruit"],
 ["Lime",30,0.7,11,0.2,"Fruit"],
 ["Clementine",47,0.9,12,0.2,"Fruit"],
 ["Tangerine",53,0.8,13,0.3,"Fruit"],
 ["Passion fruit",97,2.2,23,0.7,"Fruit"],
 ["Papaya",43,0.5,11,0.3,"Fruit"],
 ["Guava",68,2.6,14,1,"Fruit"],
 ["Lychee",66,0.8,17,0.4,"Fruit"],
 ["Dragon fruit",60,1.2,13,0.4,"Fruit"],
 ["Persimmon",70,0.6,18,0.2,"Fruit"],
 ["Star fruit",31,1,7,0.3,"Fruit"],
 ["Cranberries (fresh)",46,0.4,12,0.1,"Fruit"],
 ["Gooseberries",44,0.9,10,0.6,"Fruit"],
 ["Rhubarb",21,0.9,4.5,0.2,"Fruit"],
 ["Mulberries",43,1.4,10,0.4,"Fruit"],
 ["Coconut (fresh)",354,3.3,15,33,"Fruit"],
 ["Raisins",299,3.1,79,0.5,"Fruit"],
 ["Sultanas",296,2.7,79,0.4,"Fruit"],
 ["Dried apricots",241,3.4,63,0.5,"Fruit"],
 ["Dried figs",249,3.3,64,0.9,"Fruit"],
 ["Prunes",240,2.2,64,0.4,"Fruit"],
 ["Dried cranberries",308,0.1,82,1.4,"Fruit"],
 ["Banana chips",519,2.3,58,34,"Fruit"],
 ["Mixed dried fruit",312,2.3,79,0.5,"Fruit"],
 ["Apple sauce",68,0.2,18,0.1,"Fruit"],
 ["Fruit cocktail (canned)",72,0.4,19,0.1,"Fruit"],
 ["Broccoli",34,2.8,7,0.4,"Vegetables"],
 ["Cauliflower",25,1.9,5,0.3,"Vegetables"],
 ["Spinach",23,2.9,3.6,0.4,"Vegetables"],
 ["Kale",49,4.3,9,0.9,"Vegetables"],
 ["Carrot",41,0.9,10,0.2,"Vegetables"],
 ["Tomato",18,0.9,3.9,0.2,"Vegetables"],
 ["Cherry tomato",18,0.9,3.9,0.2,"Vegetables"],
 ["Cucumber",15,0.7,3.6,0.1,"Vegetables"],
 ["Bell pepper (red)",31,1,6,0.3,"Vegetables"],
 ["Bell pepper (green)",20,0.9,4.6,0.2,"Vegetables"],
 ["Green beans",31,1.8,7,0.1,"Vegetables"],
 ["Peas",81,5.4,14,0.4,"Vegetables"],
 ["Sweetcorn",86,3.2,19,1.2,"Vegetables"],
 ["Mushrooms",22,3.1,3.3,0.3,"Vegetables"],
 ["Onion",40,1.1,9,0.1,"Vegetables"],
 ["Red onion",40,1.1,9,0.1,"Vegetables"],
 ["Spring onion",32,1.8,7,0.2,"Vegetables"],
 ["Garlic",149,6.4,33,0.5,"Vegetables"],
 ["Lettuce (iceberg)",14,0.9,3,0.1,"Vegetables"],
 ["Lettuce (romaine)",17,1.2,3.3,0.3,"Vegetables"],
 ["Rocket",25,2.6,3.7,0.7,"Vegetables"],
 ["Courgette",17,1.2,3.1,0.3,"Vegetables"],
 ["Aubergine",25,1,6,0.2,"Vegetables"],
 ["Asparagus",20,2.2,3.9,0.1,"Vegetables"],
 ["Celery",16,0.7,3,0.2,"Vegetables"],
 ["Cabbage",25,1.3,6,0.1,"Vegetables"],
 ["Red cabbage",31,1.4,7,0.2,"Vegetables"],
 ["Brussels sprouts",43,3.4,9,0.3,"Vegetables"],
 ["Beetroot",43,1.6,10,0.2,"Vegetables"],
 ["Radish",16,0.7,3.4,0.1,"Vegetables"],
 ["Leek",61,1.5,14,0.3,"Vegetables"],
 ["Fennel",31,1.2,7,0.2,"Vegetables"],
 ["Pumpkin",26,1,6.5,0.1,"Vegetables"],
 ["Butternut squash",45,1,12,0.1,"Vegetables"],
 ["Sweet potato (baked)",90,2,21,0.2,"Vegetables"],
 ["Potato (boiled)",87,1.9,20,0.1,"Vegetables"],
 ["Potato (baked)",93,2.5,21,0.1,"Vegetables"],
 ["Mashed potato",83,2,13,3,"Vegetables"],
 ["Roast potato",149,3,26,4.5,"Vegetables"],
 ["New potatoes",75,2,17,0.1,"Vegetables"],
 ["Turnip",28,0.9,6,0.1,"Vegetables"],
 ["Swede",37,1.1,9,0.2,"Vegetables"],
 ["Parsnip",75,1.2,18,0.3,"Vegetables"],
 ["Artichoke",47,3.3,11,0.2,"Vegetables"],
 ["Okra",33,1.9,7,0.2,"Vegetables"],
 ["Bok choy",13,1.5,2.2,0.2,"Vegetables"],
 ["Watercress",11,2.3,1.3,0.1,"Vegetables"],
 ["Chard",19,1.8,3.7,0.2,"Vegetables"],
 ["Collard greens",32,3,5.4,0.6,"Vegetables"],
 ["Kohlrabi",27,1.7,6,0.1,"Vegetables"],
 ["Bean sprouts",30,3,6,0.2,"Vegetables"],
 ["Mangetout",42,2.8,7.5,0.2,"Vegetables"],
 ["Sugar snap peas",42,2.8,7.5,0.2,"Vegetables"],
 ["Olives (green)",145,1,4,15,"Vegetables"],
 ["Olives (black)",115,0.8,6,11,"Vegetables"],
 ["Sun-dried tomato",258,14,56,3,"Vegetables"],
 ["Pickled gherkin",11,0.3,2.3,0.2,"Vegetables"],
 ["Sauerkraut",19,0.9,4.3,0.1,"Vegetables"],
 ["Kimchi",23,1.7,4,0.5,"Vegetables"],
 ["Coleslaw",146,1,11,11,"Vegetables"],
 ["Mixed salad",20,1.2,3.7,0.3,"Vegetables"],
 ["Roasted veg mix",70,2,9,3,"Vegetables"],
 ["Almonds",579,21,22,50,"Nuts, seeds & fats"],
 ["Walnuts",654,15,14,65,"Nuts, seeds & fats"],
 ["Cashews",553,18,30,44,"Nuts, seeds & fats"],
 ["Peanuts",567,26,16,49,"Nuts, seeds & fats"],
 ["Pistachios",560,20,28,45,"Nuts, seeds & fats"],
 ["Pecans",691,9,14,72,"Nuts, seeds & fats"],
 ["Hazelnuts",628,15,17,61,"Nuts, seeds & fats"],
 ["Brazil nuts",659,14,12,67,"Nuts, seeds & fats"],
 ["Macadamia",718,8,14,76,"Nuts, seeds & fats"],
 ["Pine nuts",673,14,13,68,"Nuts, seeds & fats"],
 ["Mixed nuts",607,20,21,54,"Nuts, seeds & fats"],
 ["Peanut butter",588,25,20,50,"Nuts, seeds & fats"],
 ["Almond butter",614,21,19,56,"Nuts, seeds & fats"],
 ["Cashew butter",587,18,28,49,"Nuts, seeds & fats"],
 ["Tahini",595,17,21,54,"Nuts, seeds & fats"],
 ["Chia seeds",486,17,42,31,"Nuts, seeds & fats"],
 ["Flax seeds",534,18,29,42,"Nuts, seeds & fats"],
 ["Pumpkin seeds",559,30,11,49,"Nuts, seeds & fats"],
 ["Sunflower seeds",584,21,20,51,"Nuts, seeds & fats"],
 ["Sesame seeds",573,18,23,50,"Nuts, seeds & fats"],
 ["Hemp seeds",553,32,9,49,"Nuts, seeds & fats"],
 ["Poppy seeds",525,18,28,42,"Nuts, seeds & fats"],
 ["Olive oil",884,0,0,100,"Nuts, seeds & fats"],
 ["Vegetable oil",884,0,0,100,"Nuts, seeds & fats"],
 ["Coconut oil",862,0,0,100,"Nuts, seeds & fats"],
 ["Sunflower oil",884,0,0,100,"Nuts, seeds & fats"],
 ["Sesame oil",884,0,0,100,"Nuts, seeds & fats"],
 ["Butter",717,0.9,0.1,81,"Nuts, seeds & fats"],
 ["Margarine",717,0.2,0.7,80,"Nuts, seeds & fats"],
 ["Ghee",900,0,0,100,"Nuts, seeds & fats"],
 ["Lard",902,0,0,100,"Nuts, seeds & fats"],
 ["Mayonnaise",680,1,0.6,75,"Nuts, seeds & fats"],
 ["Light mayonnaise",330,0.9,8,33,"Nuts, seeds & fats"],
 ["Guacamole",150,2,8,13,"Nuts, seeds & fats"],
 ["Coconut cream",330,3,6,34,"Nuts, seeds & fats"],
 ["Nutritional yeast",325,50,36,5,"Nuts, seeds & fats"],
 ["Pesto",431,5,6,43,"Nuts, seeds & fats"],
 ["Dukkah",560,17,20,47,"Nuts, seeds & fats"],
 ["Potato crisps",536,7,53,35,"Snacks & sweets"],
 ["Lightly salted crisps",525,6,55,33,"Snacks & sweets"],
 ["Tortilla chips",489,7,63,23,"Snacks & sweets"],
 ["Popcorn (plain)",387,12,78,4.5,"Snacks & sweets"],
 ["Popcorn (sweet)",430,6,80,11,"Snacks & sweets"],
 ["Popcorn (salted)",500,9,57,28,"Snacks & sweets"],
 ["Cheese puffs",557,6,54,35,"Snacks & sweets"],
 ["Pretzels (snack)",380,10,80,3,"Snacks & sweets"],
 ["Trail mix",462,14,45,29,"Snacks & sweets"],
 ["Granola bar",471,8,64,20,"Snacks & sweets"],
 ["Cereal bar (fruit)",380,5,72,7,"Snacks & sweets"],
 ["Flapjack",450,5,60,22,"Snacks & sweets"],
 ["Rice crispy bar",400,3,82,8,"Snacks & sweets"],
 ["Chocolate (milk)",535,7.7,59,30,"Snacks & sweets"],
 ["Chocolate (dark 70%)",598,7.8,46,43,"Snacks & sweets"],
 ["Chocolate (white)",539,6,59,32,"Snacks & sweets"],
 ["Chocolate bar (filled)",490,5,62,25,"Snacks & sweets"],
 ["Chocolate biscuit",502,6,64,25,"Snacks & sweets"],
 ["Digestive biscuit",471,7,63,21,"Snacks & sweets"],
 ["Rich tea biscuit",455,7,75,14,"Snacks & sweets"],
 ["Shortbread",523,6,62,28,"Snacks & sweets"],
 ["Cookie (choc chip)",488,5,64,24,"Snacks & sweets"],
 ["Brownie",466,6,50,28,"Snacks & sweets"],
 ["Wafer biscuit",515,5,66,26,"Snacks & sweets"],
 ["Custard cream",502,5,67,24,"Snacks & sweets"],
 ["Jaffa cake",367,4,71,8,"Snacks & sweets"],
 ["Gummy sweets",343,7,77,0,"Snacks & sweets"],
 ["Jelly beans",375,0,94,0,"Snacks & sweets"],
 ["Marshmallows",318,1.8,81,0.2,"Snacks & sweets"],
 ["Toffee",459,1.5,71,19,"Snacks & sweets"],
 ["Fudge",411,1.5,78,11,"Snacks & sweets"],
 ["Caramel",382,1.5,77,8,"Snacks & sweets"],
 ["Boiled sweets",394,0,98,0,"Snacks & sweets"],
 ["Liquorice",325,3,72,3,"Snacks & sweets"],
 ["Chocolate spread",541,6,57,31,"Snacks & sweets"],
 ["Cake (sponge)",297,5,52,8,"Snacks & sweets"],
 ["Cake (chocolate)",371,5,50,17,"Snacks & sweets"],
 ["Carrot cake",415,4,52,21,"Snacks & sweets"],
 ["Cheesecake",321,5,26,22,"Snacks & sweets"],
 ["Victoria sponge",330,4,50,13,"Snacks & sweets"],
 ["Swiss roll",376,5,60,13,"Snacks & sweets"],
 ["Macaron",404,6,60,15,"Snacks & sweets"],
 ["Eclair",262,5,24,16,"Snacks & sweets"],
 ["Trifle",165,2,24,7,"Snacks & sweets"],
 ["Tiramisu",283,5,32,15,"Snacks & sweets"],
 ["Apple pie",237,2,34,11,"Snacks & sweets"],
 ["Mince pie",367,4,57,14,"Snacks & sweets"],
 ["Profiterole",330,6,28,21,"Snacks & sweets"],
 ["Ice lolly",90,0,22,0,"Snacks & sweets"],
 ["Chocolate ice lolly",130,2,17,6,"Snacks & sweets"],
 ["Sorbet",134,0.5,34,0,"Snacks & sweets"],
 ["Honey",304,0.3,82,0,"Snacks & sweets"],
 ["Maple syrup",260,0,67,0,"Snacks & sweets"],
 ["Jam",278,0.4,69,0.1,"Snacks & sweets"],
 ["Marmalade",265,0.3,65,0,"Snacks & sweets"],
 ["Nutella",539,6,58,31,"Snacks & sweets"],
 ["Golden syrup",325,0.3,79,0,"Snacks & sweets"],
 ["Peanut brittle",480,9,68,19,"Snacks & sweets"],
 ["Pizza (cheese)",266,11,33,10,"Fast food & meals"],
 ["Pizza (pepperoni)",298,12,34,13,"Fast food & meals"],
 ["Pizza (margherita)",250,11,30,9,"Fast food & meals"],
 ["Pizza (meat feast)",280,13,30,12,"Fast food & meals"],
 ["Cheeseburger",303,17,28,14,"Fast food & meals"],
 ["Hamburger",295,17,30,12,"Fast food & meals"],
 ["Double cheeseburger",375,22,30,20,"Fast food & meals"],
 ["Chicken burger",260,16,24,11,"Fast food & meals"],
 ["Bacon cheeseburger",330,18,27,17,"Fast food & meals"],
 ["Veggie burger (fast food)",230,9,28,9,"Fast food & meals"],
 ["Fries",312,3.4,41,15,"Fast food & meals"],
 ["Chips (thick cut)",233,3.4,34,9,"Fast food & meals"],
 ["Curly fries",330,4,40,17,"Fast food & meals"],
 ["Hash browns",265,3,28,15,"Fast food & meals"],
 ["Onion rings",411,5,40,26,"Fast food & meals"],
 ["Mozzarella sticks",320,13,28,17,"Fast food & meals"],
 ["Chicken wrap",215,12,22,9,"Fast food & meals"],
 ["Burrito (beef)",206,10,24,8,"Fast food & meals"],
 ["Burrito (chicken)",195,12,22,6,"Fast food & meals"],
 ["Taco (beef)",226,9,21,12,"Fast food & meals"],
 ["Quesadilla",290,13,26,15,"Fast food & meals"],
 ["Nachos (loaded)",330,9,28,20,"Fast food & meals"],
 ["Hot dog (loaded)",290,11,24,17,"Fast food & meals"],
 ["Kebab (doner)",215,15,11,13,"Fast food & meals"],
 ["Shawarma",195,16,9,11,"Fast food & meals"],
 ["Spring roll",154,4,18,7,"Fast food & meals"],
 ["Samosa",262,5,24,16,"Fast food & meals"],
 ["Fried rice (takeaway)",163,4,26,5,"Fast food & meals"],
 ["Sweet & sour chicken",180,8,24,6,"Fast food & meals"],
 ["Chow mein",150,7,18,6,"Fast food & meals"],
 ["Pad thai",170,8,22,6,"Fast food & meals"],
 ["Sushi roll",145,5,30,1,"Fast food & meals"],
 ["Nigiri",130,7,22,1,"Fast food & meals"],
 ["California roll",129,4,26,1.6,"Fast food & meals"],
 ["Ramen (bowl)",90,4,12,3,"Fast food & meals"],
 ["Pho",75,5,9,1.5,"Fast food & meals"],
 ["Fried chicken (fast food)",246,28,9,12,"Fast food & meals"],
 ["Chicken nuggets (fast food)",296,15,18,18,"Fast food & meals"],
 ["Fish & chips",195,11,21,8,"Fast food & meals"],
 ["Mac and cheese",164,7,20,6,"Fast food & meals"],
 ["Lasagne",132,8,12,6,"Fast food & meals"],
 ["Spaghetti bolognese",128,7,14,5,"Fast food & meals"],
 ["Shepherd's pie",118,7,9,6,"Fast food & meals"],
 ["Cottage pie",116,7,9,5,"Fast food & meals"],
 ["Chicken curry",130,9,7,8,"Fast food & meals"],
 ["Tikka masala",155,9,8,10,"Fast food & meals"],
 ["Korma",170,8,9,11,"Fast food & meals"],
 ["Vindaloo",140,10,6,8,"Fast food & meals"],
 ["Dal (lentil curry)",110,6,15,3,"Fast food & meals"],
 ["Biryani",165,6,24,5,"Fast food & meals"],
 ["Paella",156,9,18,5,"Fast food & meals"],
 ["Risotto (mushroom)",145,4,20,5,"Fast food & meals"],
 ["Stir fry (veg)",90,3,12,3,"Fast food & meals"],
 ["Stir fry (chicken)",120,11,8,5,"Fast food & meals"],
 ["Roast dinner (mixed)",140,9,14,5,"Fast food & meals"],
 ["Quiche",280,9,18,19,"Fast food & meals"],
 ["Cornish pasty",267,7,25,15,"Fast food & meals"],
 ["Sausage roll",312,8,25,20,"Fast food & meals"],
 ["Pork pie",376,9,24,27,"Fast food & meals"],
 ["Scotch egg",240,11,14,16,"Fast food & meals"],
 ["Toad in the hole",230,9,18,13,"Fast food & meals"],
 ["Beef stew",110,9,8,5,"Fast food & meals"],
 ["Chilli con carne",130,9,11,6,"Fast food & meals"],
 ["Minestrone soup",42,2,7,1,"Fast food & meals"],
 ["Tomato soup",58,1.5,8,2.4,"Fast food & meals"],
 ["Chicken soup",56,3,5,2.5,"Fast food & meals"],
 ["Lentil soup",60,3.5,9,1,"Fast food & meals"],
 ["Mushroom soup",70,1.5,7,4,"Fast food & meals"],
 ["Beans on toast",130,6,20,3,"Fast food & meals"],
 ["Jacket potato (beans)",110,4,20,1.5,"Fast food & meals"],
 ["Omelette (cheese)",230,15,2,18,"Fast food & meals"],
 ["Full English breakfast",200,11,9,14,"Fast food & meals"],
 ["Caesar salad (dressed)",190,9,6,15,"Fast food & meals"],
 ["Greek salad",110,3,6,8,"Fast food & meals"],
 ["Pasta salad",180,5,24,7,"Fast food & meals"],
 ["Potato salad",143,2,12,10,"Fast food & meals"],
 ["Egg fried noodles",185,5,26,7,"Fast food & meals"],
 ["Dumplings (steamed)",190,7,28,5,"Fast food & meals"],
 ["Ketchup",112,1.2,26,0.1,"Sauces & condiments"],
 ["Brown sauce",100,1,24,0.1,"Sauces & condiments"],
 ["Mustard",66,4,5,3,"Sauces & condiments"],
 ["Mayonnaise (condiment)",680,1,0.6,75,"Sauces & condiments"],
 ["BBQ sauce",172,1,40,0.6,"Sauces & condiments"],
 ["Sweet chilli sauce",225,0.5,55,0.2,"Sauces & condiments"],
 ["Soy sauce",53,8,5,0.1,"Sauces & condiments"],
 ["Sriracha",93,2,19,1,"Sauces & condiments"],
 ["Hot sauce",12,0.5,2,0.4,"Sauces & condiments"],
 ["Salsa",36,1.5,7,0.2,"Sauces & condiments"],
 ["Guacamole (condiment)",150,2,8,13,"Sauces & condiments"],
 ["Hummus (condiment)",166,8,14,10,"Sauces & condiments"],
 ["Tartar sauce",290,1,9,28,"Sauces & condiments"],
 ["Ranch dressing",430,1,6,45,"Sauces & condiments"],
 ["Caesar dressing",542,3,4,57,"Sauces & condiments"],
 ["Vinaigrette",330,0.3,5,35,"Sauces & condiments"],
 ["Balsamic vinegar",88,0.5,17,0,"Sauces & condiments"],
 ["Honey mustard",250,2,30,13,"Sauces & condiments"],
 ["Tomato pasta sauce",55,1.6,9,1.5,"Sauces & condiments"],
 ["Pesto (sauce)",431,5,6,43,"Sauces & condiments"],
 ["Curry paste",120,3,14,6,"Sauces & condiments"],
 ["Gravy",40,1,6,1,"Sauces & condiments"],
 ["Cranberry sauce",151,0.1,38,0.1,"Sauces & condiments"],
 ["Apple sauce (condiment)",68,0.2,18,0.1,"Sauces & condiments"],
 ["Mint sauce",87,1,20,0.1,"Sauces & condiments"],
 ["Tzatziki",110,4,4,8,"Sauces & condiments"],
 ["Hoisin sauce",220,2,44,3,"Sauces & condiments"],
 ["Teriyaki sauce",89,5,16,0,"Sauces & condiments"],
 ["Worcestershire sauce",78,0,19,0,"Sauces & condiments"],
 ["Tabasco",12,1.3,0.8,0.8,"Sauces & condiments"],
 ["Salad cream",348,1.5,17,30,"Sauces & condiments"],
 ["Horseradish sauce",180,1,15,13,"Sauces & condiments"],
 ["Tomato passata",35,1.5,6,0.3,"Sauces & condiments"],
 ["Coconut curry sauce",120,1.5,8,9,"Sauces & condiments"],
 ["Tomato chutney",130,1,30,0.3,"Sauces & condiments"],
 ["Mango chutney",250,0.4,60,0.3,"Sauces & condiments"],
 ["Water",0,0,0,0,"Drinks"],
 ["Sparkling water",0,0,0,0,"Drinks"],
 ["Black coffee",2,0.1,0,0,"Drinks"],
 ["Espresso",9,0.1,1.7,0.2,"Drinks"],
 ["Latte (whole milk)",55,3,5,3,"Drinks"],
 ["Cappuccino",45,2.5,4,2.5,"Drinks"],
 ["Flat white",60,3.5,5,3,"Drinks"],
 ["Americano",4,0.2,0,0,"Drinks"],
 ["Iced coffee (sweetened)",60,1,11,1.5,"Drinks"],
 ["Tea (black, no milk)",1,0,0.2,0,"Drinks"],
 ["Tea (with milk)",13,0.7,1,0.6,"Drinks"],
 ["Green tea",1,0,0.2,0,"Drinks"],
 ["Hot chocolate",90,3,15,2.5,"Drinks"],
 ["Cola",42,0,11,0,"Drinks"],
 ["Diet cola",0.4,0,0.1,0,"Drinks"],
 ["Lemonade",40,0,10,0,"Drinks"],
 ["Orange soda",48,0,12,0,"Drinks"],
 ["Ginger ale",38,0,10,0,"Drinks"],
 ["Energy drink",45,0,11,0,"Drinks"],
 ["Sugar-free energy drink",3,0,0.5,0,"Drinks"],
 ["Sports drink",26,0,6.4,0,"Drinks"],
 ["Orange juice",45,0.7,10,0.2,"Drinks"],
 ["Apple juice",46,0.1,11,0.1,"Drinks"],
 ["Cranberry juice",46,0,12,0,"Drinks"],
 ["Grape juice",60,0.3,15,0.1,"Drinks"],
 ["Pineapple juice",53,0.4,13,0.1,"Drinks"],
 ["Tomato juice",17,0.8,3.6,0.1,"Drinks"],
 ["Smoothie (fruit)",54,0.8,13,0.3,"Drinks"],
 ["Green smoothie",45,1.5,9,0.5,"Drinks"],
 ["Milkshake (vanilla)",112,3,18,3,"Drinks"],
 ["Protein shake (milk)",80,8,6,2.5,"Drinks"],
 ["Coconut water",19,0.7,3.7,0.2,"Drinks"],
 ["Lemon water",6,0.1,1.5,0,"Drinks"],
 ["Kombucha",30,0,8,0,"Drinks"],
 ["Beer (lager)",43,0.5,3.6,0,"Drinks"],
 ["Beer (ale)",45,0.5,4,0,"Drinks"],
 ["Lager (light)",29,0.3,1.5,0,"Drinks"],
 ["Stout",43,0.6,4.5,0,"Drinks"],
 ["Cider",49,0,7,0,"Drinks"],
 ["Red wine",85,0.1,2.6,0,"Drinks"],
 ["White wine",82,0.1,2.6,0,"Drinks"],
 ["Rosé wine",83,0.1,2.7,0,"Drinks"],
 ["Champagne",87,0.2,1.4,0,"Drinks"],
 ["Prosecco",80,0.2,1.5,0,"Drinks"],
 ["Vodka",231,0,0,0,"Drinks"],
 ["Whisky",250,0,0,0,"Drinks"],
 ["Gin",263,0,0,0,"Drinks"],
 ["Rum",231,0,0,0,"Drinks"],
 ["Tequila",231,0,0,0,"Drinks"],
 ["Margarita",153,0,9,0,"Drinks"],
 ["Mojito",117,0,11,0,"Drinks"],
 ["Piña colada",175,0.5,22,3,"Drinks"],
 ["Gin & tonic",80,0,8,0,"Drinks"],
 ["Bloody mary",80,1,7,0.2,"Drinks"],
 ["Aperol spritz",120,0,14,0,"Drinks"],
 ["Whey protein powder",375,75,10,5,"Protein & supplements"],
 ["Whey isolate",360,85,4,2,"Protein & supplements"],
 ["Casein protein",360,72,8,3,"Protein & supplements"],
 ["Vegan protein powder",370,70,12,5,"Protein & supplements"],
 ["Mass gainer",380,20,55,6,"Protein & supplements"],
 ["Protein bar (typical)",350,30,38,9,"Protein & supplements"],
 ["Low-sugar protein bar",330,33,30,8,"Protein & supplements"],
 ["Protein cookie",380,20,40,16,"Protein & supplements"],
 ["Protein flapjack",420,25,45,16,"Protein & supplements"],
 ["Protein yogurt",70,10,6,0.5,"Protein & supplements"],
 ["Protein milkshake (rtd)",62,8,4,1.5,"Protein & supplements"],
 ["Meal replacement shake",90,8,11,2,"Protein & supplements"],
 ["Creatine (per 5g serving est)",0,0,0,0,"Protein & supplements"],
 ["BCAA drink",10,2,0,0,"Protein & supplements"],
 ["Protein crisps",430,40,30,16,"Protein & supplements"],
 ["Protein pudding",95,10,8,2.5,"Protein & supplements"],
 ["Protein granola",420,25,45,14,"Protein & supplements"],
 ["Protein pancake mix (dry)",370,30,40,8,"Protein & supplements"],
 ["Electrolyte tablet drink",4,0,1,0,"Protein & supplements"],
 ["Greens powder",300,25,40,4,"Protein & supplements"],
 ["Sugar (white)",387,0,100,0,"Misc & extras"],
 ["Brown sugar",380,0,98,0,"Misc & extras"],
 ["Icing sugar",389,0,100,0,"Misc & extras"],
 ["Stevia",0,0,0,0,"Misc & extras"],
 ["Agave syrup",310,0,76,0,"Misc & extras"],
 ["Cocoa powder",228,20,58,14,"Misc & extras"],
 ["Cornflour",381,0.3,91,0.1,"Misc & extras"],
 ["Plain flour",364,10,76,1,"Misc & extras"],
 ["Self-raising flour",354,10,75,1,"Misc & extras"],
 ["Baking powder",53,0,28,0,"Misc & extras"],
 ["Yeast",325,40,41,8,"Misc & extras"],
 ["Gelatine",335,86,0,0,"Misc & extras"],
 ["Vinegar (white)",18,0,0.9,0,"Misc & extras"],
 ["Salt",0,0,0,0,"Misc & extras"],
 ["Black pepper",251,10,64,3.3,"Misc & extras"],
 ["Cinnamon",247,4,81,1.2,"Misc & extras"],
 ["Curry powder",325,14,56,14,"Misc & extras"],
 ["Paprika",282,14,54,13,"Misc & extras"],
 ["Chilli flakes",282,12,57,14,"Misc & extras"],
 ["Mixed herbs (dried)",259,12,60,7,"Misc & extras"],
 ["Basil (fresh)",23,3.2,2.7,0.6,"Misc & extras"],
 ["Parsley (fresh)",36,3,6,0.8,"Misc & extras"],
 ["Coriander (fresh)",23,2.1,3.7,0.5,"Misc & extras"],
 ["Ginger (fresh)",80,1.8,18,0.8,"Misc & extras"],
 ["Stock cube (1)",240,12,28,9,"Misc & extras"],
 ["Bovril/yeast extract",180,24,20,0.5,"Misc & extras"],
 ["Tomato puree",82,4.3,19,0.5,"Misc & extras"],
 ["Coconut flour",400,18,60,12,"Misc & extras"],
 ["Almond flour",571,21,20,50,"Misc & extras"],
 ["Oat flour",404,15,66,9,"Misc & extras"],
 ["Protein noodles (edamame)",340,38,28,9,"Misc & extras"],
 ["Konjac noodles",10,0,3,0,"Misc & extras"],
 ["Cauliflower rice",25,1.9,5,0.3,"Misc & extras"],
 ["Courgette spaghetti",17,1.2,3.1,0.3,"Misc & extras"],
 ["Seaweed (nori)",35,5.8,5,0.3,"Misc & extras"],
 ["Miso paste",199,12,26,6,"Misc & extras"],
 ["Tofu (smoked)",150,16,2,9,"Misc & extras"],
 ["Bone broth",40,9,1,0.5,"Misc & extras"],
 ["Pickle (dill)",11,0.3,2.3,0.2,"Misc & extras"]
];

/* Common portion hints used by the Fuel logger.
   Values are approximate grams for one everyday serving; macros still
   calculate from the per-100g database above, so users can override grams. */
const FOOD_PORTIONS = {
  /* v3.31 — EXACT-NAME portions only. A food shows a named portion ONLY if its
     name is an exact key here. Everything else falls through to grams-only chips.
     Grams entry is always available regardless. No substring/regex matching —
     that previously mis-tagged "apple sauce" as "1 medium", "veggie burger" as
     "1 egg", etc. */

  /* eggs (the egg itself — not dishes) */
  "Egg (whole)": {unit:"1 egg", grams:50},
  "Boiled egg": {unit:"1 egg", grams:50},
  "Fried egg": {unit:"1 egg", grams:46},
  "Scrambled egg": {unit:"1 egg", grams:61},
  "Duck egg": {unit:"1 egg", grams:70},
  "Quail egg": {unit:"1 egg", grams:9},

  /* whole fruit */
  "Banana": {unit:"1 medium", grams:118},
  "Apple": {unit:"1 medium", grams:182},
  "Orange": {unit:"1 medium", grams:131},
  "Pear": {unit:"1 medium", grams:178},
  "Kiwi": {unit:"1 fruit", grams:75},
  "Avocado": {unit:"1/2 avocado", grams:100},

  /* real bread & bakery (genuine slices/units) */
  "White bread": {unit:"1 slice", grams:36},
  "Wholemeal bread": {unit:"1 slice", grams:38},
  "Brown bread": {unit:"1 slice", grams:38},
  "Rye bread": {unit:"1 slice", grams:32},
  "Multigrain bread": {unit:"1 slice", grams:38},
  "Pitta bread": {unit:"1 pitta", grams:60},
  "Naan bread": {unit:"1 naan", grams:160},
  "Tortilla wrap": {unit:"1 wrap", grams:64},
  "Wholemeal wrap": {unit:"1 wrap", grams:64},
  "Bagel (plain)": {unit:"1 bagel", grams:85},
  "Bagel (cinnamon raisin)": {unit:"1 bagel", grams:85},
  "Crumpet": {unit:"1 crumpet", grams:55},

  /* protein */
  "Chicken breast (grilled)": {unit:"1 breast", grams:150},
  "Chicken breast (raw)": {unit:"1 breast", grams:170},
  "Salmon (cooked)": {unit:"1 fillet", grams:130},
  "Salmon (smoked)": {unit:"1 fillet", grams:100},
  "Salmon (raw)": {unit:"1 fillet", grams:130},
  "Sausage (pork, cooked)": {unit:"1 sausage", grams:65},
  "Chicken sausage": {unit:"1 sausage", grams:60},

  /* pizza (per slice) */
  "Pizza (cheese)": {unit:"1 slice", grams:107},
  "Pizza (pepperoni)": {unit:"1 slice", grams:111},
  "Pizza (margherita)": {unit:"1 slice", grams:107},
  "Pizza (meat feast)": {unit:"1 slice", grams:120},

  /* burgers (per burger) */
  "Cheeseburger": {unit:"1 burger", grams:113},
  "Hamburger": {unit:"1 burger", grams:110},
  "Double cheeseburger": {unit:"1 burger", grams:165},
  "Chicken burger": {unit:"1 burger", grams:150},
  "Bacon cheeseburger": {unit:"1 burger", grams:170},

  /* biscuits (per biscuit) */
  "Digestive biscuit": {unit:"1 biscuit", grams:15},
  "Rich tea biscuit": {unit:"1 biscuit", grams:10},
  "Chocolate biscuit": {unit:"1 biscuit", grams:17},
  "Wafer biscuit": {unit:"1 biscuit", grams:12},
  "Breakfast biscuit": {unit:"1 biscuit", grams:25}
};


const ACT = {sed:{m:1.2,l:"Sedentary (little/no exercise)"},light:{m:1.375,l:"Light (1–3 days/week)"},
  mod:{m:1.55,l:"Moderate (3–5 days/week)"},very:{m:1.725,l:"Very active (6–7 days/week)"},
  extra:{m:1.9,l:"Extra active (hard training/physical job)"}};

const GOALS={lose:{adj:-500,l:"Lose weight"},maintain:{adj:0,l:"Maintain"},gain:{adj:350,l:"Gain muscle"}};
